---
title: "stereoscope trial"
output: html_document
date: "2024-05-23"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load dependencies

```{r load libraries}
suppressMessages(library(Seurat))
suppressMessages(library(SeuratDisk))
suppressMessages(library(schard))
suppressMessages(library(tidyverse))
suppressMessages(library(dplyr))
suppressMessages(library(stringr))
suppressMessages(library(ggplot2))
suppressMessages(library(knitr))
suppressMessages(library(corrplot))
suppressMessages(library(sf))
suppressMessages(library(ggforce))
suppressMessages(library(magick))
suppressMessages(library(geojsonio))
suppressMessages(library(ComplexHeatmap))
suppressMessages(library(circlize))
```

# Cytospace correlation - Cell-level

```{r cytoSPACE deconvolution}

# Import metadata containnig the name of the images, width and height of the images and the corresponding Visium slide ID
info <- openxlsx::read.xlsx("~/Desktop/CIIR/data/ST-AR_Visium_samples_with file names.xlsx") %>% na.omit()
info$id <- paste0(info$Patientid, info$Tumor.area)
info <- info[-which(info$id == "BCSA2TumA1"), ]
info <- info[-which(info$id == "BCSA2TumA2"), ]

# Create a data frame to save the correlation coefficient 
cor.df <- data.frame(visium.id = info$Visium.ID,
                     id = info$id,
                     immune = NA,
                     stroma = NA,
                     tumor = NA)

for (i in 1:nrow(info)) {
  sampleid <- info$name[i]
  # Get coordinates from Seurat object, 30p image was used to run spaceranger, which corresponding to the "full resolution" image 
  patientid <- info$id[i]
  load(paste0("/Users/tili/Desktop/CIIR/data/PAM50Bulk/results/", patientid, ".RData"))
  df <- get(patientid, bcsa@images)
  temp1.coor <- df@coordinates
  temp1.coor$coor <- paste0(temp1.coor$imagerow, "x", temp1.coor$imagecol)
  temp1.coor$cellid <- rownames(temp1.coor)

  # Calculate the coordinate for full resolution image (30p image)
  temp1.coor$row_30p <- temp1.coor$imagerow 
  temp1.coor$col_30p <- temp1.coor$imagecol 

  # Digital pathology was ran on the full resolution image from the microscope, thus has a scaling factor to 30p image
  visium_h5ad_id <- info$Visum.h5ad.ID[i] %>% gsub("-Spot000001.h5ad", "", .)
  d2 <- read.delim(paste0("/Users/tili/Desktop/CIIR/results/Cell_annotation_qupath_analyzed/Cell_", visium_h5ad_id, ".txt"))

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = col_30p, y = row_30p)) + geom_point(col = "lightgreen") + theme_bw() + scale_y_reverse()

  # Get the full resolution image for scale factor calculation
  width <- info$width[i]
  height <- info$height[i]

  # Calculate scale factor
  if (patientid %in% c("BCSA2TumD3", "BCSA2TumD4", "BCSA4TumA1")) {
      scaling_factor <- 1
  } else {
      ima <- magick::image_read(paste0("/Users/tili/Desktop/CIIR/data/BCSA_images/", visium_h5ad_id, "_30p.jpg"))

      # Get the width and height of the image
      image_in <- magick::image_info(ima)
      width_30p <- image_in$width
      height_30p <- image_in$height

      # Use the height of the image to reverse the coordinates of y axis
      temp1.coor$row_30p_reverse <- height_30p - temp1.coor$row_30p

      # Check the orientation of the image
      ggplot(temp1.coor, aes(x = col_30p, y = row_30p_reverse)) + geom_point(col = "lightgreen") + theme_bw()
      scaling_factor <- height_30p / height
  }

  # Calculate the full resolution coordinates
  temp1.coor$fullcol <- temp1.coor$col_30p / scaling_factor
  temp1.coor$fullrow <- temp1.coor$row_30p / scaling_factor
  
  # Extract radius from the scale.factor json file
  r <- suppressWarnings(read.delim(paste0("/Users/tili/Desktop/CIIR/data/visium_spatial_out/", info$Visium.ID[i], "/scalefactors_json.json"), 
                  header = F)) %>% str_split(",", simplify = T)
  r <- r[1] %>% str_split(": ", simplify = T)
  r <- r[2] %>% as.numeric()
  radius <- (r / 2) / scaling_factor

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = fullcol, y = fullrow)) + geom_point(col = "lightgreen") + theme_bw() + scale_y_reverse()

  temp1.coor$fullrow_reverse <- height - temp1.coor$fullrow

  if (info$Patientid[i] == "BCSA1") {
      d2$x <- d2$Centroid.X.px
      d2$y <- d2$Centroid.Y.px
  } else {
      # The pixel size for the tiff images was wrong, we manually changed to the correct one during annotation
      # Therefore, we need to times a scaling factor to obtain the coordinates in pixels 
      d2$x <- d2$Centroid.X.µm * 5.809
      d2$y <- d2$Centroid.Y.µm * 5.809
  }

  d2$y_reverse <- height - d2$y

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = fullcol, y = fullrow_reverse)) + geom_point(col = "lightgreen") + theme_bw() 

  # Calculate the block coordinate for row and column, row is y axis, col is x axis
  temp1.coor$ymin <- temp1.coor$fullrow_reverse - radius
  temp1.coor$ymax <- temp1.coor$fullrow_reverse + radius
  temp1.coor$xmin <- temp1.coor$fullcol - radius
  temp1.coor$xmax <- temp1.coor$fullcol + radius

  # Check the orientation of the digital pathology annotation
  ggplot(d2, aes(x = x, y = y_reverse)) + geom_point(col = "lightgreen") + theme_bw()

  # If the cell falls in the square of the Visium capture area, then assign the cell id to the annotated cells
  d2$cellid <- NA
  for (j in 1:nrow(d2)) {
    x <- d2$x[j]
    y <- d2$y_reverse[j]
    temp4 <- temp1.coor[which(x > temp1.coor$xmin & x < temp1.coor$xmax & y > temp1.coor$ymin & y < temp1.coor$ymax), ]
    if (nrow(temp4) == 0) {
      d2$cellid[j] <- "Not_captured"
    } else {
      d2$cellid[j] <- temp4$cellid
    }
  }

  # Remove the cells not captured
  d4 <- d2 %>% filter(cellid != "Not_captured")

  # Count number of tumor, immune, and stroma from each visium spot
  # cell annotation output in txt file
  d5 <- d4 %>% group_by(cellid) %>% 
    dplyr::select(cellid, Classification, x, y_reverse) %>% 
    dplyr::count(Classification) %>% 
    dplyr::filter(Classification != "") %>% 
    pivot_wider(names_from = Classification, values_from = n)
  d5[is.na(d5)] <- 0

  # Change colnames from Immune Cells to Immune
  colnames(d5)[which(colnames(d5) == "Immune cells")] <- "Immune"
  
  # Calculate the total cell count and percentage
  d5$total <- rowSums(d5[,-1])
  d5$tumor_per <- d5$Tumor / d5$total
  d5$immune_per <- d5$Immune / d5$total
  d5$stroma_per <- d5$Stroma / d5$total

  # Merge coordinate with metadata
  temp1 <- merge(d5, temp1.coor, by.x = "cellid", by.y = "cellid")

  d6 <- temp1[, c(1, 12, 13, 14)]
  d5 <- merge(d5, d6, by.x = "cellid", by.y = "cellid", all.x = T, all.y = F)
  
  # Get cytospace results (Minor folder with detailed clusters)
  temp1.cyto <- read.csv(paste0("/Users/tili/Desktop/CIIR/results/cytospace/", patientid, "/fractional_abundances_by_spot.csv"),
                         row.names = 1)
  
  # Aggregate cytospace results
  temp1.cyto$cellid <- rownames(temp1.cyto)
  temp1.cyto$immune_cyto <- rowSums(temp1.cyto[which(str_detect(colnames(temp1.cyto), 
                                      "B.cells|T.cells|Macrophage|Plasmablasts|NK|Monocyte|Cycling_Myeloid|Cycling.T.cells|DCs"))])
  temp1.cyto$stroma_cyto <- rowSums(temp1.cyto[which(str_detect(colnames(temp1.cyto), 
                                      "CAFs|Endothelial|PVL|Cycling.PVL"))])
  temp1.cyto$tumor_cyto <- rowSums(temp1.cyto[which(str_detect(colnames(temp1.cyto), 
                                      "Cancer"))])
  
  # Get cytospace and digital pathology percentage results
  cyto <- temp1.cyto[, c((ncol(temp1.cyto)-3):(ncol(temp1.cyto)))]
  
  # Merge results from digital pathology and deconvolution for correlation analysis
  temp1.comb <- merge(cyto, d5, by.x = "cellid", by.y = "cellid")
  
  # Remove position where digital pathology does not detect cells
  if (length(which(rowSums(temp1.comb[, 5:7]) == 0)) > 0) {
      temp1.comb <- temp1.comb[-which(rowSums(temp1.comb[, 5:7]) == 0), ]
  }
  
  visiumid <- info$Visium.ID[i]
  id <- info$id[i]
  # Plotting and calculate correlation
  p1 <- ggplot(temp1.comb, aes(x = immune_cyto, y = immune_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("CytoSPACE Immune correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
  ggpubr::stat_cor(method = "spearman")
  print(p1)
  print(cor.test(temp1.comb$immune_cyto, temp1.comb$immune_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  immune <- cor.test(temp1.comb$immune_cyto, temp1.comb$immune_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$immune[i] <- immune$estimate
  }
  
  p2 <- ggplot(temp1.comb, aes(x = stroma_cyto, y = stroma_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("CytoSPACE Stroma correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
  ggpubr::stat_cor(method = "spearman")
  print(p2)
  print(cor.test(temp1.comb$stroma_cyto, temp1.comb$stroma_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  stroma <- cor.test(temp1.comb$stroma_cyto, temp1.comb$stroma_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$stroma[i] <- stroma$estimate
  }
  
  p3 <- ggplot(temp1.comb, aes(x = tumor_cyto, y = tumor_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("CytoSPACE Tumor correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
  ggpubr::stat_cor(method = "spearman")
  print(p3)
  print(cor.test(temp1.comb$tumor_cyto, temp1.comb$tumor_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  tumor <- cor.test(temp1.comb$tumor_cyto, temp1.comb$tumor_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$tumor[i] <- tumor$estimate
  }
}

# Remove NA in the cor.df
cor.df <- na.omit(cor.df)
cor.df <- cor.df[,-1]
rownames(cor.df) <- cor.df$id
cor.df <- cor.df[,-1]

# Plot cell-level correlation as heatmap
color_scale <- colorRamp2(c(-0.5, 0, 1), c("blue", "white", "red"))
ComplexHeatmap::Heatmap(as.matrix(cor.df), show_row_names = T, col = color_scale,
                        cluster_columns = F,
                        name = "Correlation",
                        column_title = "Cell-level Correlation with CytoSPACE", cluster_rows = F,
    cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.3f", cor.df[i, j]), x, y, gp = gpar(fontsize = 10))})

write.csv(cor.df, file = "~/Desktop/CIIR/results/CytoSPACE_cell_correlation_20250508.csv")

```

# CARD correlation - Cell-level

```{r CARD deconvolution}

info <- openxlsx::read.xlsx("~/Desktop/CIIR/data/ST-AR_Visium_samples_with file names.xlsx") %>% na.omit()
info$id <- paste0(info$Patientid, info$Tumor.area)
info <- info[-which(info$id == "BCSA2TumA1"), ]
info <- info[-which(info$id == "BCSA2TumA2"), ]

# Create a data frame to save the correlation coefficient 
cor.df <- data.frame(visium.id = info$Visium.ID,
                     id = info$id,
                     immune = NA,
                     stroma = NA,
                     tumor = NA)

for (i in 1:nrow(info)) {
  sampleid <- info$name[i]
  # Get coordinates from Seurat object, 30p image was used to run spaceranger, which corresponding to the "full resolution" image 
  patientid <- info$id[i]
  load(paste0("/Users/tili/Desktop/CIIR/data/PAM50Bulk/results/", patientid, ".RData"))
  df <- get(patientid, bcsa@images)
  temp1.coor <- df@coordinates
  temp1.coor$coor <- paste0(temp1.coor$imagerow, "x", temp1.coor$imagecol)
  temp1.coor$cellid <- rownames(temp1.coor)

  # Calculate the coordinate for full resolution image (30p image)
  temp1.coor$row_30p <- temp1.coor$imagerow 
  temp1.coor$col_30p <- temp1.coor$imagecol 

  # Digital pathology was ran on the full resolution image from the microscope, thus has a scaling factor to 30p image
  visium_h5ad_id <- info$Visum.h5ad.ID[i] %>% gsub("-Spot000001.h5ad", "", .)
  d2 <- read.delim(paste0("/Users/tili/Desktop/CIIR/results/Cell_annotation_qupath_analyzed/Cell_", visium_h5ad_id, ".txt"))

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = col_30p, y = row_30p)) + geom_point(col = "lightgreen") + theme_bw() + scale_y_reverse()

  # Get the full resolution image for scale factor calculation
  width <- info$width[i]
  height <- info$height[i]

  # Calculate scale factor
  if (patientid %in% c("BCSA2TumD3", "BCSA2TumD4", "BCSA4TumA1")) {
      scaling_factor <- 1
  } else {
      ima <- magick::image_read(paste0("/Users/tili/Desktop/CIIR/data/BCSA_images/", visium_h5ad_id, "_30p.jpg"))

      # Get the width and height of the image
      image_in <- magick::image_info(ima)
      width_30p <- image_in$width
      height_30p <- image_in$height

      # Use the height of the image to reverse the coordinates of y axis
      temp1.coor$row_30p_reverse <- height_30p - temp1.coor$row_30p

      # Check the orientation of the image
      ggplot(temp1.coor, aes(x = col_30p, y = row_30p_reverse)) + geom_point(col = "lightgreen") + theme_bw()    
    
      scaling_factor <- height_30p / height
  }

  # Calculate the full resolution coordinates
  temp1.coor$fullcol <- temp1.coor$col_30p / scaling_factor
  temp1.coor$fullrow <- temp1.coor$row_30p / scaling_factor
  
  # Extract radius from the scale.factor json file
  r <- suppressWarnings(read.delim(paste0("/Users/tili/Desktop/CIIR/data/visium_spatial_out/", info$Visium.ID[i], "/scalefactors_json.json"), 
                  header = F)) %>% str_split(",", simplify = T)
  r <- r[1] %>% str_split(": ", simplify = T)
  r <- r[2] %>% as.numeric()
  radius <- (r / 2) / scaling_factor

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = fullcol, y = fullrow)) + geom_point(col = "lightgreen") + theme_bw() + scale_y_reverse()

  temp1.coor$fullrow_reverse <- height - temp1.coor$fullrow

  if (info$Patientid[i] == "BCSA1") {
      d2$x <- d2$Centroid.X.px
      d2$y <- d2$Centroid.Y.px
  } else {
      # The pixel size for the tiff images was wrong, we manually changed to the correct one during annotation
      # Therefore, we need to times a scaling factor to obtain the coordinates in pixels 
      d2$x <- d2$Centroid.X.µm * 5.809
      d2$y <- d2$Centroid.Y.µm * 5.809
  }

  d2$y_reverse <- height - d2$y

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = fullcol, y = fullrow_reverse)) + geom_point(col = "lightgreen") + theme_bw() 

  # Calculate the block coordinate for row and column, row is y axis, col is x axis
  temp1.coor$ymin <- temp1.coor$fullrow_reverse - radius
  temp1.coor$ymax <- temp1.coor$fullrow_reverse + radius
  temp1.coor$xmin <- temp1.coor$fullcol - radius
  temp1.coor$xmax <- temp1.coor$fullcol + radius

  # Check the orientation of the digital pathology annotation
  ggplot(d2, aes(x = x, y = y_reverse)) + geom_point(col = "lightgreen") + theme_bw()

  # If the cell falls in the square of the Visium capture area, then assign the cell id to the annotated cells
  d2$cellid <- NA
  for (j in 1:nrow(d2)) {
    x <- d2$x[j]
    y <- d2$y_reverse[j]
    temp4 <- temp1.coor[which(x > temp1.coor$xmin & x < temp1.coor$xmax & y > temp1.coor$ymin & y < temp1.coor$ymax), ]
    if (nrow(temp4) == 0) {
      d2$cellid[j] <- "Not_captured"
    } else {
      d2$cellid[j] <- temp4$cellid
    }
  }

  # Remove the cells not captured
  d4 <- d2 %>% filter(cellid != "Not_captured")

  # Count number of tumor, immune, and stroma from each visium spot
  # cell annotation output in txt file
  d5 <- d4 %>% group_by(cellid) %>% 
    dplyr::select(cellid, Classification, x, y_reverse) %>% 
    dplyr::count(Classification) %>% 
    dplyr::filter(Classification != "") %>% 
    pivot_wider(names_from = Classification, values_from = n)
  d5[is.na(d5)] <- 0

  # Change colnames from Immune Cells to Immune
  colnames(d5)[which(colnames(d5) == "Immune cells")] <- "Immune"
  
  # Calculate the total cell count and percentage
  d5$total <- rowSums(d5[,-1])
  d5$tumor_per <- d5$Tumor / d5$total
  d5$immune_per <- d5$Immune / d5$total
  d5$stroma_per <- d5$Stroma / d5$total

  # Merge coordinate with metadata
  temp1 <- merge(d5, temp1.coor, by.x = "cellid", by.y = "cellid")

  d6 <- temp1[, c(1, 12, 13, 14)]
  d5 <- merge(d5, d6, by.x = "cellid", by.y = "cellid", all.x = T, all.y = F)
  
  # Get CARD results (Minor folder with detailed clusters)
  temp1.card <- read.csv(paste0("/Users/tili/Desktop/CIIR/results/CARD/", patientid, 
                                "_CARD_subset_1000_minor_common_genes.csv"), 
                         row.names = 1)
  
  # Aggregate CARD results
  temp1.card$cellid <- rownames(temp1.card)
  temp1.card$immune_card <- rowSums(temp1.card[which(str_detect(colnames(temp1.card), 
                                      "B.cells|T.cells|Macrophage|Plasmablasts|NK|Monocyte|Cycling_Myeloid|Cycling.T.cells|DCs"))])
  temp1.card$stroma_card <- rowSums(temp1.card[which(str_detect(colnames(temp1.card), 
                                      "CAFs|Endothelial|PVL|Cycling.PVL"))])
  temp1.card$tumor_card <- rowSums(temp1.card[which(str_detect(colnames(temp1.card), 
                                      "Cancer"))])
  
  # Get stero and digital pathology percentage results
  card <- temp1.card[, c((ncol(temp1.card)-3):(ncol(temp1.card)))]
  
  # Merge results from digital pathology and deconvolution for correlation analysis
  temp1.comb <- merge(card, d5, by.x = "cellid", by.y = "cellid")
  
  # Remove position where digital pathology does not detect cells
  if (length(which(rowSums(temp1.comb[, 5:7]) == 0)) > 0) {
      temp1.comb <- temp1.comb[-which(rowSums(temp1.comb[, 5:7]) == 0), ]
  }
  
  visiumid <- info$Visium.ID[i]
  id <- info$id[i]
  # Plotting and calculate correlation
  p1 <- ggplot(temp1.comb, aes(x = immune_card, y = immune_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("CARD Immune correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
  ggpubr::stat_cor(method = "spearman")
  print(p1)
  print(cor.test(temp1.comb$immune_card, temp1.comb$immune_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  immune <- cor.test(temp1.comb$immune_card, temp1.comb$immune_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$immune[i] <- immune$estimate
  }

  p2 <- ggplot(temp1.comb, aes(x = stroma_card, y = stroma_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("CARD Stroma correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
  ggpubr::stat_cor(method = "spearman")
  print(p2)
  print(cor.test(temp1.comb$stroma_card, temp1.comb$stroma_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  stroma <- cor.test(temp1.comb$stroma_card, temp1.comb$stroma_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$stroma[i] <- stroma$estimate
  }
  
  p3 <- ggplot(temp1.comb, aes(x = tumor_card, y = tumor_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("CARD Tumor correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
  ggpubr::stat_cor(method = "spearman")
  print(p3)
  print(cor.test(temp1.comb$tumor_card, temp1.comb$tumor_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  tumor <- cor.test(temp1.comb$tumor_card, temp1.comb$tumor_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$tumor[i] <- tumor$estimate
  }
}

# Remove NA in the cor.df
cor.df <- na.omit(cor.df)
cor.df <- cor.df[,-1]
rownames(cor.df) <- cor.df$id
cor.df <- cor.df[,-1]

# Plot cell-level correlation as heatmap
color_scale <- colorRamp2(c(-0.5, 0, 1), c("blue", "white", "red"))
ComplexHeatmap::Heatmap(as.matrix(cor.df), show_row_names = T, col = color_scale,
                        cluster_columns = F,
                        name = "Correlation",
                        column_title = "Cell-level Correlation with CARD", cluster_rows = F,
    cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.3f", cor.df[i, j]), x, y, gp = gpar(fontsize = 10))})

write.csv(cor.df, file = "~/Desktop/CIIR/results/CARD_cell_correlation_20250508.csv")

```

# Tangram correlation - Cell-level

```{r Tangram cell-level correlation}

info <- openxlsx::read.xlsx("~/Desktop/CIIR/data/ST-AR_Visium_samples_with file names.xlsx") %>% na.omit()
info$id <- paste0(info$Patientid, info$Tumor.area)
info <- info[-which(info$id == "BCSA2TumA1"), ]
info <- info[-which(info$id == "BCSA2TumA2"), ]

# Create a data frame to save the correlation coefficient 
cor.df <- data.frame(visium.id = info$Visium.ID,
                     id = info$id,
                     immune = NA,
                     stroma = NA,
                     tumor = NA)

for (i in 1:nrow(info)) {
  sampleid <- info$name[i]
  # Get coordinates from Seurat object, 30p image was used to run spaceranger, which corresponding to the "full resolution" image 
  patientid <- info$id[i]
  load(paste0("/Users/tili/Desktop/CIIR/data/PAM50Bulk/results/", patientid, ".RData"))
  df <- get(patientid, bcsa@images)
  temp1.coor <- df@coordinates
  temp1.coor$coor <- paste0(temp1.coor$imagerow, "x", temp1.coor$imagecol)
  temp1.coor$cellid <- rownames(temp1.coor)

  # Calculate the coordinate for full resolution image (30p image)
  temp1.coor$row_30p <- temp1.coor$imagerow 
  temp1.coor$col_30p <- temp1.coor$imagecol 

  # Digital pathology was ran on the full resolution image from the microscope, thus has a scaling factor to 30p image
  visium_h5ad_id <- info$Visum.h5ad.ID[i] %>% gsub("-Spot000001.h5ad", "", .)
  d2 <- read.delim(paste0("/Users/tili/Desktop/CIIR/results/Cell_annotation_qupath_analyzed/Cell_", visium_h5ad_id, ".txt"))

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = col_30p, y = row_30p)) + geom_point(col = "lightgreen") + theme_bw() + scale_y_reverse()

  # Get the full resolution image pixel number for scale factor calculation
  width <- info$width[i]
  height <- info$height[i]

  # Calculate scale factor
  if (patientid %in% c("BCSA2TumD3", "BCSA2TumD4", "BCSA4TumA1")) {
      scaling_factor <- 1
  } else {
      ima <- magick::image_read(paste0("/Users/tili/Desktop/CIIR/data/BCSA_images/", visium_h5ad_id, "_30p.jpg"))

      # Get the width and height of the image
      image_in <- magick::image_info(ima)
      width_30p <- image_in$width
      height_30p <- image_in$height

      # Use the height of the image to reverse the coordinates of y axis
      temp1.coor$row_30p_reverse <- height_30p - temp1.coor$row_30p

      # Check the orientation of the image
      ggplot(temp1.coor, aes(x = col_30p, y = row_30p_reverse)) + geom_point(col = "lightgreen") + theme_bw()

      scaling_factor <- height_30p / height
  }

  # Calculate the full resolution coordinates
  temp1.coor$fullcol <- temp1.coor$col_30p / scaling_factor
  temp1.coor$fullrow <- temp1.coor$row_30p / scaling_factor
  
  # Extract radius from the scale.factor json file
  r <- suppressWarnings(read.delim(paste0("/Users/tili/Desktop/CIIR/data/visium_spatial_out/", info$Visium.ID[i], "/scalefactors_json.json"), 
                  header = F)) %>% str_split(",", simplify = T)
  r <- r[1] %>% str_split(": ", simplify = T)
  r <- r[2] %>% as.numeric()
  radius <- (r / 2) / scaling_factor

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = fullcol, y = fullrow)) + geom_point(col = "lightgreen") + theme_bw() + scale_y_reverse()

  temp1.coor$fullrow_reverse <- height - temp1.coor$fullrow

  if (info$Patientid[i] == "BCSA1") {
      d2$x <- d2$Centroid.X.px
      d2$y <- d2$Centroid.Y.px
  } else {
      # The pixel size for the tiff images was wrong, we manually changed to the correct one during annotation
      # Therefore, we need to times a scaling factor to obtain the coordinates in pixels 
      d2$x <- d2$Centroid.X.µm * 5.809
      d2$y <- d2$Centroid.Y.µm * 5.809
  }

  d2$y_reverse <- height - d2$y

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = fullcol, y = fullrow_reverse)) + geom_point(col = "lightgreen") + theme_bw() 

  # Calculate the block coordinate for row and column, row is y axis, col is x axis
  temp1.coor$ymin <- temp1.coor$fullrow_reverse - radius
  temp1.coor$ymax <- temp1.coor$fullrow_reverse + radius
  temp1.coor$xmin <- temp1.coor$fullcol - radius
  temp1.coor$xmax <- temp1.coor$fullcol + radius

  # Check the orientation of the digital pathology annotation
  ggplot(d2, aes(x = x, y = y_reverse)) + geom_point(col = "lightgreen") + theme_bw()

  # If the cell falls in the square of the Visium capture area, then assign the cell id to the annotated cells
  d2$cellid <- NA
  for (j in 1:nrow(d2)) {
    x <- d2$x[j]
    y <- d2$y_reverse[j]
    temp4 <- temp1.coor[which(x > temp1.coor$xmin & x < temp1.coor$xmax & y > temp1.coor$ymin & y < temp1.coor$ymax), ]
    if (nrow(temp4) == 0) {
      d2$cellid[j] <- "Not_captured"
    } else {
      d2$cellid[j] <- temp4$cellid
    }
  }

  # Remove the cells not captured
  d4 <- d2 %>% filter(cellid != "Not_captured")

  # Count number of tumor, immune, and stroma from each visium spot
  # cell annotation output in txt file
  d5 <- d4 %>% group_by(cellid) %>% 
    dplyr::select(cellid, Classification, x, y_reverse) %>% 
    dplyr::count(Classification) %>% 
    dplyr::filter(Classification != "") %>% 
    pivot_wider(names_from = Classification, values_from = n)
  d5[is.na(d5)] <- 0

  # Change colnames from Immune Cells to Immune
  colnames(d5)[which(colnames(d5) == "Immune cells")] <- "Immune"
  
  # Calculate the total cell count and percentage
  d5$total <- rowSums(d5[,-1])
  d5$tumor_per <- d5$Tumor / d5$total
  d5$immune_per <- d5$Immune / d5$total
  d5$stroma_per <- d5$Stroma / d5$total

  # Merge coordinate with metadata
  temp1 <- merge(d5, temp1.coor, by.x = "cellid", by.y = "cellid")
  
  # Get Tangram results (Minor folder with detailed clusters)
  temp1.tan <- read.csv(paste0("/Users/tili/Desktop/CIIR/results/Tangram/Minor_HER2_genes/", info$id[i], "_Tangram.csv"))
  
  # Normalize cell type proportion so that the proportion adds up to 1
  temp1.tang <- rowSums(temp1.tan[,-1]) %>% as.data.frame() %>% 'colnames<-' ("RowSum")
  temp1.tang$X <- temp1.tan$X
  for (k in 2:ncol(temp1.tan)) {
    temp1.tang[,k+1] <- temp1.tan[,k] / temp1.tang$RowSum
    colnames(temp1.tang)[k+1] <- colnames(temp1.tan)[k]
  }
  temp1.tan <- temp1.tang[,-1]
  
  # Aggregate tangram results
  temp1.tan$immune_tan <- rowSums(temp1.tan[which(str_detect(colnames(temp1.tan), 
                                      "B.cells|T.cells|Macrophage|Plasmablasts|NK|Monocyte|Cycling_Myeloid|Cycling.T.cells|DCs"))])
  temp1.tan$stroma_tan <- rowSums(temp1.tan[which(str_detect(colnames(temp1.tan), 
                                      "CAFs|Endothelial|PVL|Cycling.PVL"))])
  temp1.tan$tumor_tan <- rowSums(temp1.tan[which(str_detect(colnames(temp1.tan), 
                                      "Cancer"))])
  
  # Get tangram and digital pathology percentage results
  tan <- temp1.tan[, c(1, (ncol(temp1.tan)-2):(ncol(temp1.tan)))]
  digital <- temp1
  
  # Merge results from digital pathology and deconvolution for correlation analysis
  temp1.comb <- merge(tan, digital, by.x = "X", by.y = "cellid")
  
  # Remove position where digital pathology does not detect cells
  if (length(which(rowSums(temp1.comb[, 5:7]) == 0)) > 0) {
      temp1.comb <- temp1.comb[-which(rowSums(temp1.comb[, 5:7]) == 0), ]
  }
  
  visiumid <- info$Visium.ID[i]
  id <- info$id[i]
  # Plotting and calculate correlation
  p1 <- ggplot(temp1.comb, aes(x = immune_tan, y = immune_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("Tangram: Immune correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
    ggpubr::stat_cor(method = "spearman")
  print(p1)
  print(cor.test(temp1.comb$immune_tan, temp1.comb$immune_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  immune <- cor.test(temp1.comb$immune_tan, temp1.comb$immune_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$immune[i] <- immune$estimate
  }
  
  p2 <- ggplot(temp1.comb, aes(x = stroma_tan, y = stroma_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("Tangram: Stroma correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
    ggpubr::stat_cor(method = "spearman")
  print(p2)
  print(cor.test(temp1.comb$stroma_tan, temp1.comb$stroma_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  stroma <- cor.test(temp1.comb$stroma_tan, temp1.comb$stroma_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$stroma[i] <- stroma$estimate
  }
  
  p3 <- ggplot(temp1.comb, aes(x = tumor_tan, y = tumor_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("Tangram: Tumor correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
  ggpubr::stat_cor(method = "spearman")
  print(p3)
  print(cor.test(temp1.comb$tumor_tan, temp1.comb$tumor_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  tumor <- cor.test(temp1.comb$tumor_tan, temp1.comb$tumor_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$tumor[i] <- tumor$estimate
  }
  
}

# Remove NA in the cor.df
cor.df <- na.omit(cor.df)
cor.df <- cor.df[,-1]
rownames(cor.df) <- cor.df$id
cor.df <- cor.df[,-1]

# Plot cell-level correlation as heatmap
color_scale <- colorRamp2(c(-0.5, 0, 1), c("blue", "white", "red"))
ComplexHeatmap::Heatmap(as.matrix(cor.df), show_row_names = T, col = color_scale,
                        cluster_columns = F,
                        name = "Correlation",
                        column_title = "Cell-level Correlation with Tangram", cluster_rows = F,
    cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.3f", cor.df[i, j]), x, y, gp = gpar(fontsize = 10))})

write.csv(cor.df, file = "~/Desktop/CIIR/results/Tangram_cell_correlation_20250508.csv")

```

# SpatialDWLS correlation - Cell-level

```{r SpatialDWLS cell-level correlation}

info <- openxlsx::read.xlsx("~/Desktop/CIIR/data/ST-AR_Visium_samples_with file names.xlsx") %>% na.omit()
info$id <- paste0(info$Patientid, info$Tumor.area)
info <- info[-which(info$id == "BCSA2TumA1"), ]
info <- info[-which(info$id == "BCSA2TumA2"), ]

# Create a data frame to save the correlation coefficient 
cor.df <- data.frame(visium.id = info$Visium.ID,
                     id = info$id,
                     immune = NA,
                     stroma = NA,
                     tumor = NA)

for (i in 1:nrow(info)) {
  sampleid <- info$name[i]
  # Get coordinates from Seurat object, 30p image was used to run spaceranger, which corresponding to the "full resolution" image 
  patientid <- info$id[i]
  load(paste0("/Users/tili/Desktop/CIIR/data/PAM50Bulk/results/", patientid, ".RData"))
  df <- get(patientid, bcsa@images)
  temp1.coor <- df@coordinates
  temp1.coor$coor <- paste0(temp1.coor$imagerow, "x", temp1.coor$imagecol)
  temp1.coor$cellid <- rownames(temp1.coor)

  # Calculate the coordinate for full resolution image (30p image)
  temp1.coor$row_30p <- temp1.coor$imagerow 
  temp1.coor$col_30p <- temp1.coor$imagecol 

  # Digital pathology was ran on the full resolution image from the microscope, thus has a scaling factor to 30p image
  visium_h5ad_id <- info$Visum.h5ad.ID[i] %>% gsub("-Spot000001.h5ad", "", .)
  d2 <- read.delim(paste0("/Users/tili/Desktop/CIIR/results/Cell_annotation_qupath_analyzed/Cell_", visium_h5ad_id, ".txt"))

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = col_30p, y = row_30p)) + geom_point(col = "lightgreen") + theme_bw() + scale_y_reverse()

  # Get the full resolution image pixel number for scale factor calculation
  width <- info$width[i]
  height <- info$height[i]

  # Calculate scale factor
  if (patientid %in% c("BCSA2TumD3", "BCSA2TumD4", "BCSA4TumA1")) {
      scaling_factor <- 1
  } else {
      ima <- magick::image_read(paste0("/Users/tili/Desktop/CIIR/data/BCSA_images/", visium_h5ad_id, "_30p.jpg"))

      # Get the width and height of the image
      image_in <- magick::image_info(ima)
      width_30p <- image_in$width
      height_30p <- image_in$height

      # Use the height of the image to reverse the coordinates of y axis
      temp1.coor$row_30p_reverse <- height_30p - temp1.coor$row_30p

      # Check the orientation of the image
      ggplot(temp1.coor, aes(x = col_30p, y = row_30p_reverse)) + geom_point(col = "lightgreen") + theme_bw()

      scaling_factor <- height_30p / height
  }

  # Calculate the full resolution coordinates
  temp1.coor$fullcol <- temp1.coor$col_30p / scaling_factor
  temp1.coor$fullrow <- temp1.coor$row_30p / scaling_factor
  
  # Extract radius from the scale.factor json file
  r <- suppressWarnings(read.delim(paste0("/Users/tili/Desktop/CIIR/data/visium_spatial_out/", info$Visium.ID[i], "/scalefactors_json.json"), 
                  header = F)) %>% str_split(",", simplify = T)
  r <- r[1] %>% str_split(": ", simplify = T)
  r <- r[2] %>% as.numeric()
  radius <- (r / 2) / scaling_factor

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = fullcol, y = fullrow)) + geom_point(col = "lightgreen") + theme_bw() + scale_y_reverse()

  temp1.coor$fullrow_reverse <- height - temp1.coor$fullrow

  if (info$Patientid[i] == "BCSA1") {
      d2$x <- d2$Centroid.X.px
      d2$y <- d2$Centroid.Y.px
  } else {
      # The pixel size for the tiff images was wrong, we manually changed to the correct one during annotation
      # Therefore, we need to times a scaling factor to obtain the coordinates in pixels 
      d2$x <- d2$Centroid.X.µm * 5.809
      d2$y <- d2$Centroid.Y.µm * 5.809
  }

  d2$y_reverse <- height - d2$y

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = fullcol, y = fullrow_reverse)) + geom_point(col = "lightgreen") + theme_bw() 

  # Calculate the block coordinate for row and column, row is y axis, col is x axis
  temp1.coor$ymin <- temp1.coor$fullrow_reverse - radius
  temp1.coor$ymax <- temp1.coor$fullrow_reverse + radius
  temp1.coor$xmin <- temp1.coor$fullcol - radius
  temp1.coor$xmax <- temp1.coor$fullcol + radius

  # Check the orientation of the digital pathology annotation
  ggplot(d2, aes(x = x, y = y_reverse)) + geom_point(col = "lightgreen") + theme_bw()

  # If the cell falls in the square of the Visium capture area, then assign the cell id to the annotated cells
  d2$cellid <- NA
  for (j in 1:nrow(d2)) {
    x <- d2$x[j]
    y <- d2$y_reverse[j]
    temp4 <- temp1.coor[which(x > temp1.coor$xmin & x < temp1.coor$xmax & y > temp1.coor$ymin & y < temp1.coor$ymax), ]
    if (nrow(temp4) == 0) {
      d2$cellid[j] <- "Not_captured"
    } else {
      d2$cellid[j] <- temp4$cellid
    }
  }

  # Remove the cells not captured
  d4 <- d2 %>% filter(cellid != "Not_captured")

  # Count number of tumor, immune, and stroma from each visium spot
  # cell annotation output in txt file
  d5 <- d4 %>% group_by(cellid) %>% 
    dplyr::select(cellid, Classification, x, y_reverse) %>% 
    dplyr::count(Classification) %>% 
    dplyr::filter(Classification != "") %>% 
    pivot_wider(names_from = Classification, values_from = n)
  d5[is.na(d5)] <- 0

  # Change colnames from Immune Cells to Immune
  colnames(d5)[which(colnames(d5) == "Immune cells")] <- "Immune"
  
  # Calculate the total cell count and percentage
  d5$total <- rowSums(d5[,-1])
  d5$tumor_per <- d5$Tumor / d5$total
  d5$immune_per <- d5$Immune / d5$total
  d5$stroma_per <- d5$Stroma / d5$total

  # Merge coordinate with metadata
  temp1 <- merge(d5, temp1.coor, by.x = "cellid", by.y = "cellid")
  
  # Get SpatialDWLS results (Minor folder with detailed clusters)
  temp1.dwls <- read.csv(paste0("/Users/tili/Desktop/CIIR/results/SpatialDWLS/", info$id[i], "_SpatialDWLS.csv"),
                         row.names = 2)
  temp1.dwls <- temp1.dwls[,-which(colnames(temp1.dwls) == "X")]
  
  # Aggregate SpatialDWLS results
  temp1.dwls$immune_dwls <- rowSums(temp1.dwls[which(str_detect(colnames(temp1.dwls), 
                                      "B_cells|T_cells|Macrophage|Plasmablasts|NK|Monocyte|Cycling_Myeloid|Cycling_T.cells|DCs"))])
  temp1.dwls$stroma_dwls <- rowSums(temp1.dwls[which(str_detect(colnames(temp1.dwls), 
                                      "CAFs|Endothelial|PVL|Cycling_PVL"))])
  temp1.dwls$tumor_dwls <- rowSums(temp1.dwls[which(str_detect(colnames(temp1.dwls), 
                                      "Cancer"))])
  temp1.dwls$X <- rownames(temp1.dwls)
  
  # Get DWLS and digital pathology percentage results
  spatialdwls <- temp1.dwls[, c(ncol(temp1.dwls)-3):(ncol(temp1.dwls))]
  digital <- temp1
  
  # Merge results from digital pathology and deconvolution for correlation analysis
  temp1.comb <- merge(spatialdwls, digital, by.x = "X", by.y = "cellid")
  
  # Remove position where digital pathology does not detect cells
  if (length(which(rowSums(temp1.comb[, 5:7]) == 0)) > 0) {
      temp1.comb <- temp1.comb[-which(rowSums(temp1.comb[, 5:7]) == 0), ]
  }
  
  visiumid <- info$Visium.ID[i]
  id <- info$id[i]
  # Plotting and calculate correlation
  p1 <- ggplot(temp1.comb, aes(x = immune_dwls, y = immune_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("SpatialDWLS: Immune correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
    ggpubr::stat_cor(method = "spearman")
  print(p1)
  print(cor.test(temp1.comb$immune_dwls, temp1.comb$immune_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  immune <- cor.test(temp1.comb$immune_dwls, temp1.comb$immune_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$immune[i] <- immune$estimate
  }
  
  p2 <- ggplot(temp1.comb, aes(x = stroma_dwls, y = stroma_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("SpatialDWLS: Stroma correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
    ggpubr::stat_cor(method = "spearman")
  print(p2)
  print(cor.test(temp1.comb$stroma_dwls, temp1.comb$stroma_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  stroma <- cor.test(temp1.comb$stroma_dwls, temp1.comb$stroma_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$stroma[i] <- stroma$estimate
  }
  
  p3 <- ggplot(temp1.comb, aes(x = tumor_dwls, y = tumor_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("SpatialDWLS: Tumor correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
  ggpubr::stat_cor(method = "spearman")
  print(p3)
  print(cor.test(temp1.comb$tumor_dwls, temp1.comb$tumor_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  tumor <- cor.test(temp1.comb$tumor_dwls, temp1.comb$tumor_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$tumor[i] <- tumor$estimate
  }
  
}

# Remove NA in the cor.df
cor.df <- na.omit(cor.df)
cor.df <- cor.df[,-1]
rownames(cor.df) <- cor.df$id
cor.df <- cor.df[,-1]

# Plot cell-level correlation as heatmap
color_scale <- colorRamp2(c(-0.5, 0, 1), c("blue", "white", "red"))
ComplexHeatmap::Heatmap(as.matrix(cor.df), show_row_names = T, col = color_scale,
                        cluster_columns = F,
                        name = "Correlation",
                        column_title = "Cell-level Correlation with SpatialDWLS", cluster_rows = F,
    cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.3f", cor.df[i, j]), x, y, gp = gpar(fontsize = 10))})

write.csv(cor.df, file = "~/Desktop/CIIR/results/SpatialDWLS_cell_correlation_20250508.csv")

```

# Cell2location correlation - Cell-level

```{r Cell2location cell-level correlation}

info <- openxlsx::read.xlsx("~/Desktop/CIIR/data/ST-AR_Visium_samples_with file names.xlsx") %>% na.omit()
info$id <- paste0(info$Patientid, info$Tumor.area)
info <- info[-which(info$id == "BCSA2TumA1"), ]
info <- info[-which(info$id == "BCSA2TumA2"), ]

# Create a data frame to save the correlation coefficient 
cor.df <- data.frame(visium.id = info$Visium.ID,
                     id = info$id,
                     immune = NA,
                     stroma = NA,
                     tumor = NA)

for (i in 1:nrow(info)) {
  sampleid <- info$name[i]
  # Get coordinates from Seurat object, 30p image was used to run spaceranger, which corresponding to the "full resolution" image 
  patientid <- info$id[i]
  load(paste0("/Users/tili/Desktop/CIIR/data/PAM50Bulk/results/", patientid, ".RData"))
  df <- get(patientid, bcsa@images)
  temp1.coor <- df@coordinates
  temp1.coor$coor <- paste0(temp1.coor$imagerow, "x", temp1.coor$imagecol)
  temp1.coor$cellid <- rownames(temp1.coor)

  # Calculate the coordinate for full resolution image (30p image)
  temp1.coor$row_30p <- temp1.coor$imagerow 
  temp1.coor$col_30p <- temp1.coor$imagecol 

  # Digital pathology was ran on the full resolution image from the microscope, thus has a scaling factor to 30p image
  visium_h5ad_id <- info$Visum.h5ad.ID[i] %>% gsub("-Spot000001.h5ad", "", .)
  d2 <- read.delim(paste0("/Users/tili/Desktop/CIIR/results/Cell_annotation_qupath_analyzed/Cell_", visium_h5ad_id, ".txt"))

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = col_30p, y = row_30p)) + geom_point(col = "lightgreen") + theme_bw() + scale_y_reverse()

  # Get the full resolution image pixel number for scale factor calculation
  width <- info$width[i]
  height <- info$height[i]

  # Calculate scale factor
  if (patientid %in% c("BCSA2TumD3", "BCSA2TumD4", "BCSA4TumA1")) {
      scaling_factor <- 1
  } else {
      ima <- magick::image_read(paste0("/Users/tili/Desktop/CIIR/data/BCSA_images/", visium_h5ad_id, "_30p.jpg"))

      # Get the width and height of the image
      image_in <- magick::image_info(ima)
      width_30p <- image_in$width
      height_30p <- image_in$height

      # Use the height of the image to reverse the coordinates of y axis
      temp1.coor$row_30p_reverse <- height_30p - temp1.coor$row_30p

      # Check the orientation of the image
      ggplot(temp1.coor, aes(x = col_30p, y = row_30p_reverse)) + geom_point(col = "lightgreen") + theme_bw()

      scaling_factor <- height_30p / height
  }

  # Calculate the full resolution coordinates
  temp1.coor$fullcol <- temp1.coor$col_30p / scaling_factor
  temp1.coor$fullrow <- temp1.coor$row_30p / scaling_factor
  
  # Extract radius from the scale.factor json file
  r <- suppressWarnings(read.delim(paste0("/Users/tili/Desktop/CIIR/data/visium_spatial_out/", info$Visium.ID[i], "/scalefactors_json.json"), 
                  header = F)) %>% str_split(",", simplify = T)
  r <- r[1] %>% str_split(": ", simplify = T)
  r <- r[2] %>% as.numeric()
  radius <- (r / 2) / scaling_factor

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = fullcol, y = fullrow)) + geom_point(col = "lightgreen") + theme_bw() + scale_y_reverse()

  temp1.coor$fullrow_reverse <- height - temp1.coor$fullrow

  if (info$Patientid[i] == "BCSA1") {
      d2$x <- d2$Centroid.X.px
      d2$y <- d2$Centroid.Y.px
  } else {
      # The pixel size for the tiff images was wrong, we manually changed to the correct one during annotation
      # Therefore, we need to times a scaling factor to obtain the coordinates in pixels 
      d2$x <- d2$Centroid.X.µm * 5.809
      d2$y <- d2$Centroid.Y.µm * 5.809
  }

  d2$y_reverse <- height - d2$y

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = fullcol, y = fullrow_reverse)) + geom_point(col = "lightgreen") + theme_bw() 

  # Calculate the block coordinate for row and column, row is y axis, col is x axis
  temp1.coor$ymin <- temp1.coor$fullrow_reverse - radius
  temp1.coor$ymax <- temp1.coor$fullrow_reverse + radius
  temp1.coor$xmin <- temp1.coor$fullcol - radius
  temp1.coor$xmax <- temp1.coor$fullcol + radius

  # Check the orientation of the digital pathology annotation
  ggplot(d2, aes(x = x, y = y_reverse)) + geom_point(col = "lightgreen") + theme_bw()

  # If the cell falls in the square of the Visium capture area, then assign the cell id to the annotated cells
  d2$cellid <- NA
  for (j in 1:nrow(d2)) {
    x <- d2$x[j]
    y <- d2$y_reverse[j]
    temp4 <- temp1.coor[which(x > temp1.coor$xmin & x < temp1.coor$xmax & y > temp1.coor$ymin & y < temp1.coor$ymax), ]
    if (nrow(temp4) == 0) {
      d2$cellid[j] <- "Not_captured"
    } else {
      d2$cellid[j] <- temp4$cellid
    }
  }

  # Remove the cells not captured
  d4 <- d2 %>% filter(cellid != "Not_captured")

  # Count number of tumor, immune, and stroma from each visium spot
  # cell annotation output in txt file
  d5 <- d4 %>% group_by(cellid) %>% 
    dplyr::select(cellid, Classification, x, y_reverse) %>% 
    dplyr::count(Classification) %>% 
    dplyr::filter(Classification != "") %>%     
    pivot_wider(names_from = Classification, values_from = n)
  d5[is.na(d5)] <- 0

  # Change colnames from Immune Cells to Immune
  colnames(d5)[which(colnames(d5) == "Immune cells")] <- "Immune"
  
  # Calculate the total cell count and percentage
  d5$total <- rowSums(d5[,-1])
  d5$tumor_per <- d5$Tumor / d5$total
  d5$immune_per <- d5$Immune / d5$total
  d5$stroma_per <- d5$Stroma / d5$total

  # Merge coordinate with metadata
  temp1 <- merge(d5, temp1.coor, by.x = "cellid", by.y = "cellid")
  
  # Get cell2location results (Minor folder with detailed clusters)
  temp1.cel2 <- read.csv(paste0("/Users/tili/Desktop/CIIR/results/cell2location/", info$id[i], "_q05.csv"))
  colnames(temp1.cel2) <- gsub("q05cell_abundance_w_sf_", "", colnames(temp1.cel2))
  
  # Normalize cell type proportion so that the proportion adds up to 1
  temp1.cell2 <- rowSums(temp1.cel2[,-1]) %>% as.data.frame() %>% 'colnames<-' ("RowSum")
  temp1.cell2$X <- temp1.cel2$X
  for (k in 2:ncol(temp1.cel2)) {
    temp1.cell2[,k+1] <- temp1.cel2[,k] / temp1.cell2$RowSum
    colnames(temp1.cell2)[k+1] <- colnames(temp1.cel2)[k]
  }
  temp1.cel2 <- temp1.cell2[,-1]
  
  # Aggregate cell2location results
  temp1.cel2$immune_cel2 <- rowSums(temp1.cel2[which(str_detect(colnames(temp1.cel2), 
                                      "B.cells|T.cells|Macrophage|Plasmablasts|NK|Monocyte|Cycling_Myeloid|Cycling.T.cells|DCs"))])
  temp1.cel2$stroma_cel2 <- rowSums(temp1.cel2[which(str_detect(colnames(temp1.cel2), 
                                      "CAFs|Endothelial|PVL|Cycling.PVL"))])
  temp1.cel2$tumor_cel2 <- rowSums(temp1.cel2[which(str_detect(colnames(temp1.cel2), 
                                      "Cancer"))])
  
  # Get cell2location and digital pathology percentage results
  cell2 <- temp1.cel2[, c(1, (ncol(temp1.cel2)-2):(ncol(temp1.cel2)))]
  digital <- temp1
  
  # Merge results from digital pathology and deconvolution for correlation analysis
  temp1.comb <- merge(cell2, digital, by.x = "X", by.y = "cellid")
  
  # Remove position where digital pathology does not detect cells
  if (length(which(rowSums(temp1.comb[, 5:7]) == 0)) > 0) {
      temp1.comb <- temp1.comb[-which(rowSums(temp1.comb[, 5:7]) == 0), ]
  }
  
  # Save the combined results from digital pathology and deconvolution
  write.csv(temp1.comb, file = paste0("/Users/tili/Desktop/CIIR/results/cell2location/Merged_correlation_results/",
                                      info$id[i], "_correlation_matrix.csv"))
  
  visiumid <- info$Visium.ID[i]
  id <- info$id[i]
  # Plotting and calculate correlation
  p1 <- ggplot(temp1.comb, aes(x = immune_cel2, y = immune_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("Cell2location: Immune correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
    ggpubr::stat_cor(method = "spearman")
  print(p1)
  print(cor.test(temp1.comb$immune_cel2, temp1.comb$immune_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  immune <- cor.test(temp1.comb$immune_cel2, temp1.comb$immune_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$immune[i] <- immune$estimate
  }
  
  p2 <- ggplot(temp1.comb, aes(x = stroma_cel2, y = stroma_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("Cell2location: Stroma correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
    ggpubr::stat_cor(method = "spearman")
  print(p2)
  print(cor.test(temp1.comb$stroma_cel2, temp1.comb$stroma_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  stroma <- cor.test(temp1.comb$stroma_cel2, temp1.comb$stroma_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$stroma[i] <- stroma$estimate
  }
  
  p3 <- ggplot(temp1.comb, aes(x = tumor_cel2, y = tumor_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("Cell2location: Tumor correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
  ggpubr::stat_cor(method = "spearman")
  print(p3)
  print(cor.test(temp1.comb$tumor_cel2, temp1.comb$tumor_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  tumor <- cor.test(temp1.comb$tumor_cel2, temp1.comb$tumor_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$tumor[i] <- tumor$estimate
  }
  
}

# Remove NA in the cor.df
cor.df <- na.omit(cor.df)
cor.df <- cor.df[,-1]
rownames(cor.df) <- cor.df$id
cor.df <- cor.df[,-1]

# Plot cell-level correlation as heatmap
color_scale <- colorRamp2(c(-0.5, 0, 1), c("blue", "white", "red"))
ComplexHeatmap::Heatmap(as.matrix(cor.df), show_row_names = T, col = color_scale,
                        cluster_columns = F,
                        name = "Correlation",
                        column_title = "Cell-level Correlation with Cell2location", cluster_rows = F,
    cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.3f", cor.df[i, j]), x, y, gp = gpar(fontsize = 10))})

write.csv(cor.df, file = "~/Desktop/CIIR/results/Cell2location_cell_correlation_20250508.csv")

```

# Stereoscope Correlation - Cell-level

```{r cell-level correlation with stereoscope}

# Load metadata
info <- openxlsx::read.xlsx("~/Desktop/CIIR/data/ST-AR_Visium_samples_with file names.xlsx") %>% na.omit()
info$id <- paste0(info$Patientid, info$Tumor.area)
info <- info[-which(info$id == "BCSA2TumA1"), ]
info <- info[-which(info$id == "BCSA2TumA2"), ]

# Create a data frame to save the correlation coefficient 
cor.df <- data.frame(visium.id = info$Visium.ID,
                     id = info$id,
                     immune = NA,
                     stroma = NA,
                     tumor = NA)

for (i in 1:nrow(info)) {
  sampleid <- info$name[i]
  # Get digital correlation results
  #temp1 <- schard::h5ad2data.frame(paste0("~/Desktop/CIIR/data/Annotation/", info$Visum.h5ad.ID[2]), "obs")
  #colnames(temp1)[1] <- "cellid"
  
  # Get coordinates from Seurat object, 30p image was used to run spaceranger, which corresponding to the "full resolution" image 
  patientid <- info$id[i]
  load(paste0("/Users/tili/Desktop/CIIR/data/PAM50Bulk/results/", patientid, ".RData"))
  df <- get(patientid, bcsa@images)
  temp1.coor <- df@coordinates
  temp1.coor$coor <- paste0(temp1.coor$imagerow, "x", temp1.coor$imagecol)
  temp1.coor$cellid <- rownames(temp1.coor)

  # Calculate the coordinate for full resolution image (30p image)
  temp1.coor$row_30p <- temp1.coor$imagerow 
  temp1.coor$col_30p <- temp1.coor$imagecol 

  # Digital pathology was ran on the full resolution image from the microscope, thus has a scaling factor to 30p image
  #d2 <- dig
  #d2$x <- round(d2$x, digits = 3)
  #d2$y <- round(d2$y, digits = 3)
  visium_h5ad_id <- info$Visum.h5ad.ID[i] %>% gsub("-Spot000001.h5ad", "", .)
  d2 <- read.delim(paste0("/Users/tili/Desktop/CIIR/results/Cell_annotation_qupath_analyzed/Cell_", visium_h5ad_id, ".txt"))

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = col_30p, y = row_30p)) + geom_point(col = "lightgreen") + theme_bw() + scale_y_reverse()

  # Get the full resolution image for scale factor calculation
  #full_res_file <- info$Visum.h5ad.ID[i] %>% gsub("1.h5ad", "", .)
  #full_res_name <- list.files("/Users/tili/Desktop/CIIR/data/BCSA_images/")[list.files("/Users/tili/Desktop/CIIR/data/BCSA_images/") %>%
  #                                                           grep(full_res_file, .)]
  #ima <- magick::image_read(paste0("/Users/tili/Desktop/CIIR/data/BCSA_images/", full_res_name))

  # Get the width and height of the image
  #image_in <- magick::image_info(ima)
  #width <- image_in$width
  #height <- image_in$height
  width <- info$width[i]
  height <- info$height[i]

  # Calculate scale factor
  if (patientid %in% c("BCSA2TumD3", "BCSA2TumD4", "BCSA4TumA1")) {
    scaling_factor <- 1
  } else {
    ima <- magick::image_read(paste0("/Users/tili/Desktop/CIIR/data/BCSA_images/", visium_h5ad_id, "_30p.jpg"))

    # Get the width and height of the image
    image_in <- magick::image_info(ima)
    width_30p <- image_in$width
    height_30p <- image_in$height

    # Use the height of the image to reverse the coordinates of y axis
    temp1.coor$row_30p_reverse <- height_30p - temp1.coor$row_30p

    # Check the orientation of the image
    ggplot(temp1.coor, aes(x = col_30p, y = row_30p_reverse)) + geom_point(col = "lightgreen") + theme_bw()
    
    scaling_factor <- height_30p / height
  }

  # Calculate the full resolution coordinates
  temp1.coor$fullcol <- temp1.coor$col_30p / scaling_factor
  temp1.coor$fullrow <- temp1.coor$row_30p / scaling_factor
  
  # Extract radius from the scale.factor json file
  r <- suppressWarnings(read.delim(paste0("/Users/tili/Desktop/CIIR/data/visium_spatial_out/", info$Visium.ID[i], "/scalefactors_json.json"), 
                  header = F)) %>% str_split(",", simplify = T)
  r <- r[1] %>% str_split(": ", simplify = T)
  r <- r[2] %>% as.numeric()
  radius <- (r / 2) / scaling_factor

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = fullcol, y = fullrow)) + geom_point(col = "lightgreen") + theme_bw() + scale_y_reverse()

  temp1.coor$fullrow_reverse <- height - temp1.coor$fullrow

  if (info$Patientid[i] == "BCSA1") {
      d2$x <- d2$Centroid.X.px
      d2$y <- d2$Centroid.Y.px
  } else {
      # The pixel size for the tiff images was wrong, we manually changed to the correct one during annotation
      # Therefore, we need to times a scaling factor to obtain the coordinates in pixels 
      d2$x <- d2$Centroid.X.µm * 5.809
      d2$y <- d2$Centroid.Y.µm * 5.809
  }

  d2$y_reverse <- height - d2$y

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = fullcol, y = fullrow_reverse)) + geom_point(col = "lightgreen") + theme_bw() 

  # Calculate the block coordinate for row and column, row is y axis, col is x axis
  temp1.coor$ymin <- temp1.coor$fullrow_reverse - radius
  temp1.coor$ymax <- temp1.coor$fullrow_reverse + radius
  temp1.coor$xmin <- temp1.coor$fullcol - radius
  temp1.coor$xmax <- temp1.coor$fullcol + radius

  # Check the orientation of the digital pathology annotation
  ggplot(d2, aes(x = x, y = y_reverse)) + geom_point(col = "lightgreen") + theme_bw()

  # If the cell falls in the square of the Visium capture area, then assign the cell id to the annotated cells
  d2$cellid <- NA
  for (j in 1:nrow(d2)) {
    x <- d2$x[j]
    y <- d2$y_reverse[j]
    temp4 <- temp1.coor[which(x > temp1.coor$xmin & x < temp1.coor$xmax & y > temp1.coor$ymin & y < temp1.coor$ymax), ]
    if (nrow(temp4) == 0) {
      d2$cellid[j] <- "Not_captured"
    } else {
      d2$cellid[j] <- temp4$cellid
    }
  }

  # Remove the cells not captured
  d4 <- d2 %>% filter(cellid != "Not_captured")

  # Count number of tumor, immune, and stroma from each visium spot
  # cell annotation output in txt file
  d5 <- d4 %>% group_by(cellid) %>% 
    dplyr::select(cellid, Classification, x, y_reverse) %>% 
    dplyr::count(Classification) %>% 
    dplyr::filter(Classification != "") %>% 
    pivot_wider(names_from = Classification, values_from = n)
  d5[is.na(d5)] <- 0

  # Change colnames from Immune Cells to Immune
  colnames(d5)[which(colnames(d5) == "Immune cells")] <- "Immune"
  
  # Calculate the total cell count and percentage
  d5$total <- rowSums(d5[,-1])
  d5$tumor_per <- d5$Tumor / d5$total
  d5$immune_per <- d5$Immune / d5$total
  d5$stroma_per <- d5$Stroma / d5$total

  # Merge coordinate with metadata
  temp1 <- merge(d5, temp1.coor, by.x = "cellid", by.y = "cellid")
  #write.csv(temp1, file = paste0("/Users/tili/Desktop/CIIR/results/to_hosein_cell_annotation_results/",
  #                               patientid, "_cell_annotation.csv"))

  # Align the high resolution image with the high resolution coordinates
  #selected <- d5$cellid
  #ima <- magick::image_read("/Users/tili/Desktop/CIIR/data/visium_spatial_out/V19T26-031_A1/tissue_hires_image.png")

  # Get the width and height of the image
  #image_in <- magick::image_info(ima)
  #width_hires <- image_in$width
  #height_hires <- image_in$height

  #temp1$hires_col <- temp1$imagecol * bcsa@images$BCSA3TumB2@scale.factors$hires
  #temp1$hires_row_reverse <- height_hires - temp1$imagerow * bcsa@images$BCSA3TumB2@scale.factors$hires

  # Plot the scatter plot on top of the HE images
  #temp1 %>% filter(cellid %in% selected) %>% 
  #  ggplot(aes(x = hires_col, y = hires_row_reverse)) + 
  #  annotation_raster(ima, ymin = 0, ymax= height_hires, xmin = 0, xmax = width_hires) + 
  #  geom_point(col = "lightgreen", size = 0.7, alpha = 0.5) + theme_bw()

  d6 <- temp1[, c(1, 12, 13, 14)]
  d5 <- merge(d5, d6, by.x = "cellid", by.y = "cellid", all.x = T, all.y = F)

  # Get Stereoscope results (Minor folder with detailed clusters)
  file_path <- paste0("/Users/tili/Desktop/CIIR/results/stereoscope/", patientid, ".mtx/")
  file.name <- list.files(file_path)
  temp1.stero <- read.delim(paste0(file_path, file.name))

  # Aggregate steroscope results
  temp1.stero$immune_stero <- rowSums(temp1.stero[which(str_detect(colnames(temp1.stero),
                                      "B_cells|T_cells|Macrophage|Plasmablasts|NK|Monocyte|Cycling_Myeloid|Cycling_T.cells|DCs"))])
  temp1.stero$stroma_stero <- rowSums(temp1.stero[which(str_detect(colnames(temp1.stero), 
                                      "CAFs|Endothelial|PVL|Cycling_PVL"))])
  temp1.stero$tumor_stero <- rowSums(temp1.stero[which(str_detect(colnames(temp1.stero), 
                                      "Cancer"))])
  
  # Get stero and digital pathology percentage results
  stero <- temp1.stero[, c(1, (ncol(temp1.stero)-2):(ncol(temp1.stero)))]

  temp1.comb <- merge(stero, d5, by.x = "X", by.y = "coor", all.x = F, all.y = T)
  temp1.comb <- na.omit(temp1.comb)
  
  # Remove position where digital pathology does not detect cells
  if (length(which(rowSums(temp1.comb[, 6:8]) == 0)) > 0) {
      temp1.comb <- temp1.comb[-which(rowSums(temp1.comb[, 6:8]) == 0), ]
  }

  visiumid <- info$Visium.ID[i]
  id <- info$id[i]
  # Plotting and calculate correlation
  p1 <- ggplot(temp1.comb, aes(x = immune_stero, y = immune_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("Stereoscope: Cell-level Immune correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
    ggpubr::stat_cor(method = "spearman")
  print(p1)
  print(cor.test(temp1.comb$immune_stero, temp1.comb$immune_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  immune <- cor.test(temp1.comb$immune_stero, temp1.comb$immune_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$immune[i] <- immune$estimate
  }

  p2 <- ggplot(temp1.comb, aes(x = stroma_stero, y = stroma_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("Stereoscope: Cell-level Stroma correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
    ggpubr::stat_cor(method = "spearman")
  print(p2)
  print(cor.test(temp1.comb$stroma_stero, temp1.comb$stroma_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  stroma <- cor.test(temp1.comb$stroma_stero, temp1.comb$stroma_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$stroma[i] <- stroma$estimate
  }
  
  p3 <- ggplot(temp1.comb, aes(x = tumor_stero, y = tumor_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("Stereoscope: Cell-level Tumor correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
    ggpubr::stat_cor(method = "spearman")
  print(p3)
  print(cor.test(temp1.comb$tumor_stero, temp1.comb$tumor_per, method = "spearman"))

  # Save the correlation coefficient to the data frame
  tumor <- cor.test(temp1.comb$tumor_stero, temp1.comb$tumor_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$tumor[i] <- tumor$estimate
  }
  
}

# Remove NA in the cor.df
cor.df <- na.omit(cor.df)
cor.df <- cor.df[,-1]
rownames(cor.df) <- cor.df$id
cor.df <- cor.df[,-1]

# Plot cell-level correlation as heatmap
color_scale <- colorRamp2(c(-0.5, 0, 1), c("blue", "white", "red"))
ComplexHeatmap::Heatmap(as.matrix(cor.df), show_row_names = T, col = color_scale,
                        cluster_columns = F,
                        name = "Correlation",
                        column_title = "Cell-level Correlation with Stereoscope", cluster_rows = F,
    cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.3f", cor.df[i, j]), x, y, gp = gpar(fontsize = 10))})

write.csv(cor.df, file = "~/Desktop/CIIR/results/Stereoscope_cell_correlation_20250508.csv")

```

# RCTD correlation - Cell-level

```{r RCTD cell-level correlation}

info <- openxlsx::read.xlsx("~/Desktop/CIIR/data/ST-AR_Visium_samples_with file names.xlsx") %>% na.omit()
info$id <- paste0(info$Patientid, info$Tumor.area)
info <- info[-which(info$id == "BCSA2TumA1"), ]
info <- info[-which(info$id == "BCSA2TumA2"), ]

# Create a data frame to save the correlation coefficient 
cor.df <- data.frame(visium.id = info$Visium.ID,
                     id = info$id,
                     immune = NA,
                     stroma = NA,
                     tumor = NA)

for (i in 1:nrow(info)) {
  sampleid <- info$name[i]
  # Get coordinates from Seurat object, 30p image was used to run spaceranger, which corresponding to the "full resolution" image 
  patientid <- info$id[i]
  load(paste0("/Users/tili/Desktop/CIIR/data/PAM50Bulk/results/", patientid, ".RData"))
  df <- get(patientid, bcsa@images)
  temp1.coor <- df@coordinates
  temp1.coor$coor <- paste0(temp1.coor$imagerow, "x", temp1.coor$imagecol)
  temp1.coor$cellid <- rownames(temp1.coor)

  # Calculate the coordinate for full resolution image (30p image)
  temp1.coor$row_30p <- temp1.coor$imagerow 
  temp1.coor$col_30p <- temp1.coor$imagecol 

  # Digital pathology was ran on the full resolution image from the microscope, thus has a scaling factor to 30p image
  visium_h5ad_id <- info$Visum.h5ad.ID[i] %>% gsub("-Spot000001.h5ad", "", .)
  d2 <- read.delim(paste0("/Users/tili/Desktop/CIIR/results/Cell_annotation_qupath_analyzed/Cell_", visium_h5ad_id, ".txt"))

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = col_30p, y = row_30p)) + geom_point(col = "lightgreen") + theme_bw() + scale_y_reverse()

  # Get the full resolution image pixel number for scale factor calculation
  width <- info$width[i]
  height <- info$height[i]

  # Calculate scale factor
  if (patientid %in% c("BCSA2TumD3", "BCSA2TumD4", "BCSA4TumA1")) {
    scaling_factor <- 1
  } else {
    ima <- magick::image_read(paste0("/Users/tili/Desktop/CIIR/data/BCSA_images/", visium_h5ad_id, "_30p.jpg"))

    # Get the width and height of the image
    image_in <- magick::image_info(ima)
    width_30p <- image_in$width
    height_30p <- image_in$height

    # Use the height of the image to reverse the coordinates of y axis
    temp1.coor$row_30p_reverse <- height_30p - temp1.coor$row_30p

    # Check the orientation of the image
    ggplot(temp1.coor, aes(x = col_30p, y = row_30p_reverse)) + geom_point(col = "lightgreen") + theme_bw()
    
    scaling_factor <- height_30p / height
  }

  # Calculate the full resolution coordinates
  temp1.coor$fullcol <- temp1.coor$col_30p / scaling_factor
  temp1.coor$fullrow <- temp1.coor$row_30p / scaling_factor
  
  # Extract radius from the scale.factor json file
  r <- suppressWarnings(read.delim(paste0("/Users/tili/Desktop/CIIR/data/visium_spatial_out/", info$Visium.ID[i], "/scalefactors_json.json"), 
                  header = F)) %>% str_split(",", simplify = T)
  r <- r[1] %>% str_split(": ", simplify = T)
  r <- r[2] %>% as.numeric()
  radius <- (r / 2) / scaling_factor

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = fullcol, y = fullrow)) + geom_point(col = "lightgreen") + theme_bw() + scale_y_reverse()

  temp1.coor$fullrow_reverse <- height - temp1.coor$fullrow

  if (info$Patientid[i] == "BCSA1") {
      d2$x <- d2$Centroid.X.px
      d2$y <- d2$Centroid.Y.px
  } else {
      # The pixel size for the tiff images was wrong, we manually changed to the correct one during annotation
      # Therefore, we need to times a scaling factor to obtain the coordinates in pixels 
      d2$x <- d2$Centroid.X.µm * 5.809
      d2$y <- d2$Centroid.Y.µm * 5.809
  }

  d2$y_reverse <- height - d2$y

  # Check the orientation of the image
  ggplot(temp1.coor, aes(x = fullcol, y = fullrow_reverse)) + geom_point(col = "lightgreen") + theme_bw() 

  # Calculate the block coordinate for row and column, row is y axis, col is x axis
  temp1.coor$ymin <- temp1.coor$fullrow_reverse - radius
  temp1.coor$ymax <- temp1.coor$fullrow_reverse + radius
  temp1.coor$xmin <- temp1.coor$fullcol - radius
  temp1.coor$xmax <- temp1.coor$fullcol + radius

  # Check the orientation of the digital pathology annotation
  ggplot(d2, aes(x = x, y = y_reverse)) + geom_point(col = "lightgreen") + theme_bw()

  # If the cell falls in the square of the Visium capture area, then assign the cell id to the annotated cells
  d2$cellid <- NA
  for (j in 1:nrow(d2)) {
    x <- d2$x[j]
    y <- d2$y_reverse[j]
    temp4 <- temp1.coor[which(x > temp1.coor$xmin & x < temp1.coor$xmax & y > temp1.coor$ymin & y < temp1.coor$ymax), ]
    if (nrow(temp4) == 0) {
      d2$cellid[j] <- "Not_captured"
    } else {
      d2$cellid[j] <- temp4$cellid
    }
  }

  # Remove the cells not captured
  d4 <- d2 %>% filter(cellid != "Not_captured")

  # Count number of tumor, immune, and stroma from each visium spot
  # cell annotation output in txt file
  d5 <- d4 %>% group_by(cellid) %>% 
    dplyr::select(cellid, Classification, x, y_reverse) %>% 
    dplyr::count(Classification) %>% 
    dplyr::filter(Classification != "") %>% 
    pivot_wider(names_from = Classification, values_from = n)
  d5[is.na(d5)] <- 0

  # Change colnames from Immune Cells to Immune
  colnames(d5)[which(colnames(d5) == "Immune cells")] <- "Immune"
  
  # Calculate the total cell count and percentage
  d5$total <- rowSums(d5[,-1])
  d5$tumor_per <- d5$Tumor / d5$total
  d5$immune_per <- d5$Immune / d5$total
  d5$stroma_per <- d5$Stroma / d5$total

  # Merge coordinate with metadata
  temp1 <- merge(d5, temp1.coor, by.x = "cellid", by.y = "cellid")
  
  # Get RCTD results (Minor folder with detailed clusters)
  temp1.rctd <- read.delim(paste0("/Users/tili/Desktop/CIIR/results/RCTD/", info$id[i], "_norm.txt"))
  
  # Aggregate RCTD results
  temp1.rctd$immune_rctd <- rowSums(temp1.rctd[which(str_detect(colnames(temp1.rctd), 
                                      "B_cells|T_cells|Macrophage|Plasmablasts|NK|Monocyte|Cycling_Myeloid|Cycling_T.cells|DCs"))])
  temp1.rctd$stroma_rctd <- rowSums(temp1.rctd[which(str_detect(colnames(temp1.rctd), 
                                      "CAFs|Endothelial|PVL|Cycling_PVL"))])
  temp1.rctd$tumor_rctd <- rowSums(temp1.rctd[which(str_detect(colnames(temp1.rctd), 
                                      "Cancer"))])
  temp1.rctd$X <- rownames(temp1.rctd)
  
  # Get RCTD and digital pathology percentage results
  rctd <- temp1.rctd[, c((ncol(temp1.rctd)-3):(ncol(temp1.rctd)))]
  digital <- temp1
  
  # Merge results from digital pathology and deconvolution for correlation analysis
  temp1.comb <- merge(rctd, digital, by.x = "X", by.y = "cellid")
  
  # Remove position where digital pathology does not detect cells
  if (length(which(rowSums(temp1.comb[, 5:7]) == 0)) > 0) {
      temp1.comb <- temp1.comb[-which(rowSums(temp1.comb[, 5:7]) == 0), ]
  }
  
  visiumid <- info$Visium.ID[i]
  id <- info$id[i]
  # Plotting and calculate correlation
  p1 <- ggplot(temp1.comb, aes(x = immune_rctd, y = immune_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("RCTD: Immune correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
    ggpubr::stat_cor(method = "spearman")
  print(p1)
  print(cor.test(temp1.comb$immune_rctd, temp1.comb$immune_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  immune <- cor.test(temp1.comb$immune_rctd, temp1.comb$immune_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$immune[i] <- immune$estimate
  }
  
  p2 <- ggplot(temp1.comb, aes(x = stroma_rctd, y = stroma_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("RCTD: Stroma correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
    ggpubr::stat_cor(method = "spearman")
  print(p2)
  print(cor.test(temp1.comb$stroma_rctd, temp1.comb$stroma_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  stroma <- cor.test(temp1.comb$stroma_rctd, temp1.comb$stroma_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$stroma[i] <- stroma$estimate
  }
  
  p3 <- ggplot(temp1.comb, aes(x = tumor_rctd, y = tumor_per)) + geom_point() + theme_bw() +
    ggtitle(paste0("RCTD: Tumor correlation - ", visiumid, " - ", id)) + geom_smooth(method = "lm") + 
  ggpubr::stat_cor(method = "spearman")
  print(p3)
  print(cor.test(temp1.comb$tumor_rctd, temp1.comb$tumor_per, method = "spearman"))
  
  # Save the correlation coefficient to the data frame
  tumor <- cor.test(temp1.comb$tumor_rctd, temp1.comb$tumor_per, method = "spearman")
  if (visiumid == cor.df$visium.id[i] & id == cor.df$id[i]) {
     cor.df$tumor[i] <- tumor$estimate
  }
  
}

# Remove NA in the cor.df
cor.df <- na.omit(cor.df)
cor.df <- cor.df[,-1]
rownames(cor.df) <- cor.df$id
cor.df <- cor.df[,-1]

# Plot tissue-level correlation as heatmap
color_scale <- colorRamp2(c(-0.5, 0, 1), c("blue", "white", "red"))
ComplexHeatmap::Heatmap(as.matrix(cor.df), show_row_names = T, col = color_scale,
                        cluster_columns = F,
                        name = "Correlation",
                        column_title = "Cell-level Correlation with RCTD", cluster_rows = F,
    cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.3f", cor.df[i, j]), x, y, gp = gpar(fontsize = 10))})

write.csv(cor.df, file = "~/Desktop/CIIR/results/RCTD_cell_correlation_20250508.csv")

```

# Comparison between stereoscope, cytoSPACE, Tangram, DWLS, RCTD, Cell2location, and CARD

```{r Comparison}

# Load the results 
stereo <- read.csv("/Users/tili/Desktop/CIIR/results/Stereoscope_cell_correlation_20250508.csv", row.names = 1)
stereo$Method <- rep("Stereoscope", nrow(stereo))
stereo$Strategy <- rep("Cell-level", nrow(stereo))

cyto <- read.csv("/Users/tili/Desktop/CIIR/results/CytoSPACE_cell_correlation_20250508.csv", row.names = 1)
cyto$Method <- rep("CytoSPACE", nrow(cyto))
cyto$Strategy <- rep("Cell-level", nrow(cyto))

card <- read.csv("/Users/tili/Desktop/CIIR/results/CARD_cell_correlation_20250508.csv", row.names = 1)
card$Method <- rep("CARD", nrow(card))
card$Strategy <- rep("Cell-level", nrow(card))

tangram <- read.csv("/Users/tili/Desktop/CIIR/results/Tangram_cell_correlation_20250508.csv", row.names = 1)
tangram$Method <- rep("Tangram", nrow(tangram))
tangram$Strategy <- rep("Cell-level", nrow(tangram))

dwls <- read.csv("/Users/tili/Desktop/CIIR/results/SpatialDWLS_cell_correlation_20250508.csv", row.names = 1)
dwls$Method <- rep("SpatialDWLS", nrow(dwls))
dwls$Strategy <- rep("Cell-level", nrow(dwls))

rctd <- read.csv("/Users/tili/Desktop/CIIR/results/RCTD_cell_correlation_20250508.csv", row.names = 1)
rctd$Method <- rep("RCTD", nrow(rctd))
rctd$Strategy <- rep("Cell-level", nrow(rctd))

cell2location <- read.csv("/Users/tili/Desktop/CIIR/results/Cell2location_cell_correlation_20250508.csv", row.names = 1)
cell2location$Method <- rep("Cell2location", nrow(cell2location))
cell2location$Strategy <- rep("Cell-level", nrow(cell2location))

### Cell-level correlation
cor.matrix <- rbind(stereo, cyto, card, tangram, dwls, rctd, cell2location)

im <- cor.matrix %>% dplyr::select(immune, Method, Strategy)

stro <- cor.matrix %>% dplyr::select(stroma, Method, Strategy)

tum <- cor.matrix %>% dplyr::select(tumor, Method, Strategy)

# Boxplot with 7 deconvolution methods - Immune
p1 <- ggplot(im, aes(x = Method, y = immune, fill = Method)) + 
  geom_violin() +
  geom_boxplot(width = 0.15, fill = "white") + 
  ggbeeswarm::geom_beeswarm(cex = 2, priority = "density", alpha = 0.5) +
  theme_bw() +
  ggtitle("Immune") + ylab("Spearman Correlation Coefficient") + 
  scale_fill_manual(values = c("grey", "#E2C8D8", "#E07E35", "#74b69f", "#A9C4E6", "#F2CCA0", "#D1392B")) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major = element_blank(),   
        panel.grid.minor = element_blank(),
        axis.text = element_text(size = 12, colour = "black"),
        legend.title = element_text(size = 14),    
        legend.text = element_text(size = 12),
        plot.title = element_text(size = 18),
        axis.title = element_text(size = 15)) + ylim(c(-0.25, 1)) + xlab("")

# Statistics
an <- aov(im$immune ~ im$Method)
TukeyHSD(an)

im$Method <- factor(im$Method)
dunn.test(im$immune, im$Method, method = "bh")

# Boxplot with 7 deconvolution methods - Stroma
p2 <- ggplot(stro, aes(x = Method, y = stroma, fill = Method)) + 
  geom_violin() +
  geom_boxplot(width = 0.15, fill = "white") + 
  ggbeeswarm::geom_beeswarm(cex = 2, priority = "density", alpha = 0.5) +
  theme_bw() +
  ggtitle("Stroma") + ylab("") + 
  scale_fill_manual(values = c("grey", "#E2C8D8", "#E07E35", "#74b69f", "#A9C4E6", "#F2CCA0", "#D1392B")) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major = element_blank(),   
        panel.grid.minor = element_blank(),
        axis.text = element_text(size = 12, colour = "black"),
        legend.title = element_text(size = 14),    
        legend.text = element_text(size = 12),
        plot.title = element_text(size = 18)) + ylim(c(-0.25, 1)) + xlab("")

# Statistics
an <- aov(stro$stroma ~ stro$Method)
TukeyHSD(an)

stro$Method <- factor(stro$Method)
dunn.test(stro$stroma, stro$Method, method = "bh")

# Boxplot with 7 deconvolution methods - Tumor
p3 <- ggplot(tum, aes(x = Method, y = tumor, fill = Method)) + 
  geom_violin() +
  geom_boxplot(width = 0.15, fill = "white") + 
  ggbeeswarm::geom_beeswarm(cex = 2, priority = "density", alpha = 0.5) +
  theme_bw() +
  ggtitle("Tumor") + ylab("") + 
  scale_fill_manual(values = c("grey", "#E2C8D8", "#E07E35", "#74b69f", "#A9C4E6", "#F2CCA0", "#D1392B")) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major = element_blank(),   
        panel.grid.minor = element_blank(),
        axis.text = element_text(size = 12, colour = "black"),
        legend.title = element_text(size = 14),    
        legend.text = element_text(size = 12),
        plot.title = element_text(size = 18)) + ylim(c(-0.25, 1)) + xlab("") 

# Statistics
an <- aov(tum$tumor ~ tum$Method)
TukeyHSD(an)

tum$Method <- factor(tum$Method)
dunn.test(tum$tumor, tum$Method, method = "bh")

p1 + p2 + p3 + patchwork::plot_layout(guides = "collect")

# Plot tumor correlation as heatmap
ComplexHeatmap::Heatmap(as.matrix(tum), show_row_names = T,
                        name = "Tumor Correlation", cluster_rows = F,
    cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.3f", tum[i, j]), x, y, gp = gpar(fontsize = 10))})

# Plot stroma correlation as heatmap
ComplexHeatmap::Heatmap(as.matrix(stro), show_row_names = T,
                        name = "Stroma Correlation", cluster_rows = F,
    cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.3f", stro[i, j]), x, y, gp = gpar(fontsize = 10))})

# Plot immune correlation as heatmap
ComplexHeatmap::Heatmap(as.matrix(im), show_row_names = T,
                        name = "Immune Correlation", cluster_rows = F,
                        cluster_columns = F,
    cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.3f", im[i, j]), x, y, gp = gpar(fontsize = 10))})

```

# Session info

```{r session info}
sessionInfo()
```

