---
title: "SpatialVDJ_visualization"
output: html_document
date: "2025-04-16"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load dependencies

```{r load libraries}
suppressMessages(library(Seurat))
suppressMessages(library(SeuratDisk))
suppressMessages(library(schard))
suppressMessages(library(tidyverse))
suppressMessages(library(dplyr))
suppressMessages(library(stringr))
suppressMessages(library(ggplot2))
suppressMessages(library(knitr))
suppressMessages(library(corrplot))
suppressMessages(library(CARD))
suppressMessages(library(SeuratDisk))
suppressMessages(library(patchwork))
suppressMessages(library(STutility))
suppressMessages(library(semla))
suppressMessages(library(GSVA))
suppressMessages(library(METAFlux))
suppressMessages(library(infercnv))
suppressMessages(library(ComplexHeatmap))
suppressMessages(library(biomaRt))
suppressMessages(library(SPOTlight))
suppressMessages(library(clusterProfiler))
suppressMessages(library(GSEABase))
suppressMessages(library(org.Hs.eg.db))
suppressMessages(library(enrichplot))
suppressMessages(library(ggchromatic))
suppressMessages(library(circlize))
suppressMessages(library(dendextend))
```

## BCSA2 SpatialVDJ plotting 

```{r SpatialVDJ and Quath}

vdj <- read_tsv("/Users/tili/Desktop/CIIR/data/SpatialVDJ_forZenodo/data/breast_cancer/1_LR-SpatialVDJ/postfiltered_matrices/newtables_run86-BC-SA2_TumE2-filtered-filter-readcount-0-umi-count.tsv")

meta <- read.csv("/Users/tili/Desktop/CIIR/data/SpatialVDJ_forZenodo/data/breast_cancer/1_LR-SpatialVDJ/clone_list/P1_all_ontissue_clone_list.csv")

# Fix the different name of ST barcodes
vdj$st_barcode <- paste0(vdj$st_barcode, "-1")

# Plot clone 0
clone0 <- vdj$'0'
names(clone0) <- vdj$st_barcode

e2 <- read.csv("~/Desktop/CIIR/results/cell2location/Merged_correlation_results/BCSA2TumE2_correlation_matrix.csv") %>% 
  dplyr::select(X, immune_cel2, stroma_cel2, tumor_cel2, col_30p, row_30p_reverse) 
e2$col <- e2$col_30p * 0.1370614
e2$row_reverse <- e2$row_30p_reverse * 0.1370614
e2$X <- paste0("TumE2_", e2$X)

clone_spot <- paste0("TumE2_", names(clone0[clone0 > 0]))
e2 <- e2[which(e2$X %in% clone_spot),]

# Add HE image on the back
ima <- magick::image_read("/Users/tili/Desktop/CIIR/data/visium_spatial_out/V10F24-114_D1/tissue_hires_image.png")
image_in <- magick::image_info(ima)
width <- image_in$width
height <- image_in$height

spots <- as.data.frame(clone0)
spots$spotid <- paste0("TumE2_", rownames(spots))
spots <- spots[which(spots$spotid %in% e2$X),]
e2 <- merge(e2, spots, by.x = "X", by.y = "spotid", all.x = T, all.y = T)

# Save the results
e2_all_clone0_spots <- e2

# Plot the visium spots
ggplot(e2, aes(y = row_reverse, x =col)) + 
  annotation_raster(ima, ymin = 0, ymax= height, xmin = 0, xmax = width) +
  geom_point(col = "#FFDE18") + theme_bw() + ylim(c(0, 1900)) + xlim(c(0, 1900))

# Merge Qupath cell level annotation with visium spot ID
i = 12
sampleid <- info$name[i]
# Get coordinates from Seurat object, 30p image was used to run spaceranger, which corresponding to the "full resolution" image 
patientid <- info$id[i]
load(paste0("/Users/tili/Desktop/CIIR/data/PAM50Bulk/results/", patientid, ".RData"))
df <- get(patientid, bcsa@images)
temp1.coor <- df@coordinates
temp1.coor$coor <- paste0(temp1.coor$imagerow, "x", temp1.coor$imagecol)
temp1.coor$cellid <- rownames(temp1.coor)

# Calculate the coordinate for full resolution image (30p image)
temp1.coor$row_30p <- temp1.coor$imagerow 
temp1.coor$col_30p <- temp1.coor$imagecol 

# Digital pathology was ran on the full resolution image from the microscope, thus has a scaling factor to 30p image
visium_h5ad_id <- info$Visum.h5ad.ID[i] %>% gsub("-Spot000001.h5ad", "", .)
d2 <- read.delim(paste0("/Users/tili/Desktop/CIIR/results/Cell_annotation_qupath_analyzed/Cell_", visium_h5ad_id, ".txt"))

# Get the full resolution image pixel number for scale factor calculation
width <- info$width[i]
height <- info$height[i]

# Calculate scale factor
ima <- magick::image_read(paste0("/Users/tili/Desktop/CIIR/data/BCSA_images/", visium_h5ad_id, "_30p.jpg"))
      
# Get the width and height of the image
image_in <- magick::image_info(ima)
width_30p <- image_in$width
height_30p <- image_in$height

# Use the height of the image to reverse the coordinates of y axis
temp1.coor$row_30p_reverse <- height_30p - temp1.coor$row_30p

scaling_factor <- height_30p / height

# Calculate the full resolution coordinates
temp1.coor$fullcol <- temp1.coor$col_30p / scaling_factor
temp1.coor$fullrow <- temp1.coor$row_30p / scaling_factor
  
# Extract radius from the scale.factor json file
r <- suppressWarnings(read.delim(paste0("/Users/tili/Desktop/CIIR/data/visium_spatial_out/", info$Visium.ID[i], "/scalefactors_json.json"), 
                  header = F)) %>% str_split(",", simplify = T)
r <- r[1] %>% str_split(": ", simplify = T)
r <- r[2] %>% as.numeric()
radius <- (r / 2) / scaling_factor
  
temp1.coor$fullrow_reverse <- height - temp1.coor$fullrow

# The pixel size for the tiff images was wrong, we manually changed to the correct one during annotation
# Therefore, we need to times a scaling factor to obtain the coordinates in pixels 
d2$x <- d2$Centroid.X.µm * 5.809
d2$y <- d2$Centroid.Y.µm * 5.809

d2$y_reverse <- height - d2$y

# Calculate the block coordinate for row and column, row is y axis, col is x axis
temp1.coor$ymin <- temp1.coor$fullrow_reverse - radius
temp1.coor$ymax <- temp1.coor$fullrow_reverse + radius
temp1.coor$xmin <- temp1.coor$fullcol - radius
temp1.coor$xmax <- temp1.coor$fullcol + radius

# If the cell falls in the square of the Visium capture area, then assign the cell id to the annotated cells
d2$cellid <- NA
for (j in 1:nrow(d2)) {
    x <- d2$x[j]
    y <- d2$y_reverse[j]
    temp4 <- temp1.coor[which(x > temp1.coor$xmin & x < temp1.coor$xmax & y > temp1.coor$ymin & y < temp1.coor$ymax), ]
    if (nrow(temp4) == 0) {
      d2$cellid[j] <- "Not_captured"
    } else {
      d2$cellid[j] <- temp4$cellid
    }
}

# Remove the cells not captured
d4 <- d2 %>% filter(cellid != "Not_captured")
d4$cellid <- paste0("TumE2_", d4$cellid)

# Filter out cells belong to spots with clone event
d5 <- d4[which(d4$cellid %in% e2$X),]
top2 <- spots %>% dplyr::arrange(spots$clone0) %>% tail(n = 2)

# Filter out two spots with the most clone events
d6 <- d5[which(d5$cellid %in% top2$spotid),]

# Plot the two selected spots on HE image
e2 %>% dplyr::filter(X %in% d6$cellid) %>% 
  ggplot(aes(y = row_reverse, x =col)) + 
  annotation_raster(ima, ymin = 0, ymax= height, xmin = 0, xmax = width) +
  geom_point(col = "#FFDE18") + theme_bw() + ylim(c(0, 1900)) + xlim(c(0, 1900))

# Save the objectID for qupath annotation
write.csv(d6, file = "/Users/tili/Desktop/CIIR/results/tables/BCSA2TumE2_spatialVDJ_clone0_top2_event_spots_qupath_cell_annotation_output.csv")

```

## BCSA3 SpatialVDJ plotting 

```{r BCSA3 SpatialVDJ and Quath}

vdj <- read_tsv("/Users/tili/Desktop/CIIR/data/SpatialVDJ_forZenodo/data/breast_cancer/1_LR-SpatialVDJ/postfiltered_matrices/newtables_run86-BC-SA3_TumA1-filtered-filter-readcount-0-umi-count.tsv")

meta <- read.csv("/Users/tili/Desktop/CIIR/data/SpatialVDJ_forZenodo/data/breast_cancer/1_LR-SpatialVDJ/clone_list/P2_all_ontissue_clone_list.csv")

# Fix the different name of ST barcodes
vdj$st_barcode <- paste0(vdj$st_barcode, "-1")

# Plot clone 61
clone61 <- vdj$'61'
names(clone61) <- vdj$st_barcode

a1 <- read.csv("~/Desktop/CIIR/results/cell2location/Merged_correlation_results/BCSA3TumA1_correlation_matrix.csv") %>% 
  dplyr::select(X, immune_cel2, stroma_cel2, tumor_cel2, col_30p, row_30p_reverse) 
a1$col <- a1$col_30p * 0.1264143
a1$row_reverse <- a1$row_30p_reverse * 0.1264143
a1$X <- paste0("TumA1_", a1$X)

clone_spot <- paste0("TumA1_", names(clone61[clone61 > 0]))
a1 <- a1[which(a1$X %in% clone_spot),]

# Add HE image on the back
ima <- magick::image_read("/Users/tili/Desktop/CIIR/data/visium_spatial_out/V19T26-031_D1/tissue_hires_image.png")
image_in <- magick::image_info(ima)
width <- image_in$width
height <- image_in$height

spots <- as.data.frame(clone61)
spots$spotid <- paste0("TumA1_", rownames(spots))
spots <- spots[which(spots$spotid %in% a1$X),]
a1 <- merge(a1, spots, by.x = "X", by.y = "spotid", all.x = T, all.y = T)

# Save the data
a1_all_clone61_spots <- a1

# Plot the visium spots
ggplot(a1, aes(y = row_reverse, x =col)) + 
  annotation_raster(ima, ymin = 0, ymax = height, xmin = 0, xmax = width) +
  geom_point(col = "#FFDE18", size = 0.8) + theme_bw() + ylim(c(0, 1900)) + xlim(c(0, 1900))

# Merge Qupath cell level annotation with visium spot ID
i = 13
sampleid <- info$name[i]
# Get coordinates from Seurat object, 30p image was used to run spaceranger, which corresponding to the "full resolution" image 
patientid <- info$id[i]
load(paste0("/Users/tili/Desktop/CIIR/data/PAM50Bulk/results/", patientid, ".RData"))
df <- get(patientid, bcsa@images)
temp1.coor <- df@coordinates
temp1.coor$coor <- paste0(temp1.coor$imagerow, "x", temp1.coor$imagecol)
temp1.coor$cellid <- rownames(temp1.coor)

# Calculate the coordinate for full resolution image (30p image)
temp1.coor$row_30p <- temp1.coor$imagerow 
temp1.coor$col_30p <- temp1.coor$imagecol 

# Digital pathology was ran on the full resolution image from the microscope, thus has a scaling factor to 30p image
visium_h5ad_id <- info$Visum.h5ad.ID[i] %>% gsub("-Spot000001.h5ad", "", .)
d2 <- read.delim(paste0("/Users/tili/Desktop/CIIR/results/Cell_annotation_qupath_analyzed/Cell_", visium_h5ad_id, ".txt"))

# Get the full resolution image pixel number for scale factor calculation
width <- info$width[i]
height <- info$height[i]

# Calculate scale factor
ima <- magick::image_read(paste0("/Users/tili/Desktop/CIIR/data/BCSA_images/", visium_h5ad_id, "_30p.jpg"))
      
# Get the width and height of the image
image_in <- magick::image_info(ima)
width_30p <- image_in$width
height_30p <- image_in$height

# Use the height of the image to reverse the coordinates of y axis
temp1.coor$row_30p_reverse <- height_30p - temp1.coor$row_30p

scaling_factor <- height_30p / height

# Calculate the full resolution coordinates
temp1.coor$fullcol <- temp1.coor$col_30p / scaling_factor
temp1.coor$fullrow <- temp1.coor$row_30p / scaling_factor
  
# Extract radius from the scale.factor json file
r <- suppressWarnings(read.delim(paste0("/Users/tili/Desktop/CIIR/data/visium_spatial_out/", info$Visium.ID[i], "/scalefactors_json.json"), 
                  header = F)) %>% str_split(",", simplify = T)
r <- r[1] %>% str_split(": ", simplify = T)
r <- r[2] %>% as.numeric()
radius <- (r / 2) / scaling_factor
  
temp1.coor$fullrow_reverse <- height - temp1.coor$fullrow

# The pixel size for the tiff images was wrong, we manually changed to the correct one during annotation
# Therefore, we need to times a scaling factor to obtain the coordinates in pixels 
d2$x <- d2$Centroid.X.µm * 5.809
d2$y <- d2$Centroid.Y.µm * 5.809

d2$y_reverse <- height - d2$y

# Calculate the block coordinate for row and column, row is y axis, col is x axis
temp1.coor$ymin <- temp1.coor$fullrow_reverse - radius
temp1.coor$ymax <- temp1.coor$fullrow_reverse + radius
temp1.coor$xmin <- temp1.coor$fullcol - radius
temp1.coor$xmax <- temp1.coor$fullcol + radius

# If the cell falls in the square of the Visium capture area, then assign the cell id to the annotated cells
d2$cellid <- NA
for (j in 1:nrow(d2)) {
    x <- d2$x[j]
    y <- d2$y_reverse[j]
    temp4 <- temp1.coor[which(x > temp1.coor$xmin & x < temp1.coor$xmax & y > temp1.coor$ymin & y < temp1.coor$ymax), ]
    if (nrow(temp4) == 0) {
      d2$cellid[j] <- "Not_captured"
    } else {
      d2$cellid[j] <- temp4$cellid
    }
}

# Remove the cells not captured
d4 <- d2 %>% filter(cellid != "Not_captured")
d4$cellid <- paste0("TumA1_", d4$cellid)

# Filter out cells belong to spots with clone event
d5 <- d4[which(d4$cellid %in% a1$X),]
top2 <- spots %>% dplyr::arrange(spots$clone61) %>% tail(n = 2)

# Filter out two spots with the most clone events
d6 <- d5[which(d5$cellid %in% top2$spotid),]

ima <- magick::image_read("/Users/tili/Desktop/CIIR/data/visium_spatial_out/V19T26-031_D1/tissue_hires_image.png")
image_in <- magick::image_info(ima)
width <- image_in$width
height <- image_in$height

# Plot the selected spot on HE image (clone61: TumA1_ATACGTTATGCACGGA-1)
a1 %>% dplyr::filter(X == "TumA1_ATACGTTATGCACGGA-1") %>% 
  ggplot(aes(y = row_reverse, x =col)) + 
  annotation_raster(ima, ymin = 0, ymax= height, xmin = 0, xmax = width) +
  geom_point(col = "#FFDE18") + theme_bw() + ylim(c(0, 1900)) + xlim(c(0, 1900))

# Save the objectID for qupath annotation
write.csv(d6, file = "/Users/tili/Desktop/CIIR/results/tables/BCSA3TumA1_spatialVDJ_T_cells_clone61_event_spots_qupath_cell_annotation_output.csv")

```

## Create a geojson file to map SpatilVDJ spots on annotated HE images

```{r Map SpatialVDJ spots}

# Function to create a circle as an sf polygon
create_circle <- function(x, y, r, n = 6) {
  theta <- seq(0, 2 * pi, length.out = n)
  x_coords <- x + r * cos(theta)
  y_coords <- y + r * sin(theta)
  coords <- cbind(x_coords, y_coords)
  coords <- rbind(coords, coords[1, ])  # Ensure the polygon is closed
  polygon <- st_polygon(list(coords))
  return(st_sfc(polygon))
}

circle_data <- qupath %>% 
  dplyr::filter(patient == "BCSA2") %>% 
  dplyr::filter(spot == "TumE2_ACACCACATAATTAGC-1")

# Extract the columns with full resolution coordinates
radius <- bcsa2@images$BCSA2TumE2@scale.factors$spot / 2
circle_data$radius <- rep(radius, nrow(circle_data))

# Apply the function to create sf polygons for each circle
circle_data$geometry <- mapply(create_circle, circle_data$x, circle_data$y, 
                               circle_data$radius, SIMPLIFY = FALSE)

circle_sf <- st_as_sf(circle_data, coords = c("x", "y"), crs = 4326, agr = "constant")

# Save to GeoJSON
geojson_write(circle_sf, file = "/Users/tili/Desktop/CIIR/results/colocalization/BCSA2TumE2_IG_clone0_circle_data.geojson")

################## BCSA3TumA1 #######################

circle_data <- qupath %>% 
  dplyr::filter(patient == "BCSA3") %>% 
  dplyr::filter(spot == "TumA1_ATACGTTATGCACGGA-1")

# Extract the columns with full resolution coordinates
radius <- bcsa3@images$BCSA3TumA1@scale.factors$spot / 2
circle_data$radius <- rep(radius, nrow(circle_data))

# Apply the function to create sf polygons for each circle
circle_data$geometry <- mapply(create_circle, circle_data$x, circle_data$y, 
                               circle_data$radius, SIMPLIFY = FALSE)

circle_sf <- st_as_sf(circle_data, coords = c("x", "y"), crs = 4326, agr = "constant")

# Save to GeoJSON
geojson_write(circle_sf, file = "/Users/tili/Desktop/CIIR/results/colocalization/BCSA3TumA1_TR_clone61_circle_data.geojson")

```

## Deconvolution for the selected spots with VDJ clones

```{r Deconvolution for VDJ clones}

############### BCSA2TumE2 - Clone0: TumE2_ACACCACATAATTAGC-1

e2 <- read.csv("/Users/tili/Desktop/CIIR/results/cell2location/BCSA2TumE2_q05.csv")
colnames(e2) <- gsub("q05cell_abundance_w_sf_", "", colnames(e2))

# Aggregate to major level
e2$Endothelial <- rowSums(e2[which(str_detect(colnames(e2), 
                               "Endothelial"))])
e2$CAFs <- rowSums(e2[which(str_detect(colnames(e2), 
                               "CAF"))])
e2$PVLs <- rowSums(e2[which(str_detect(colnames(e2), 
                                      "PVL|Cycling.PVL"))])
e2$Cancer <- rowSums(e2[which(str_detect(colnames(e2), 
                                      "Cancer"))])
e2$B.cells <- rowSums(e2[which(str_detect(colnames(e2), 
                                      "B.cells"))])
e2$T.cells_ILCs <- rowSums(e2[which(str_detect(colnames(e2), 
                                      "T.cells|NK"))])
e2$Plasmablasts <- rowSums(e2[which(str_detect(colnames(e2), 
                                      "Plasmablasts"))])
e2$Myeloid <- rowSums(e2[which(str_detect(colnames(e2), 
                                      "DCs|Monocyte|Macrophage|Cycling_Myeloid"))])

e2_agg <- e2[,c(1, 28, 31:37)]

e2 <- e2_agg %>% dplyr::filter(X == "ACACCACATAATTAGC-1") %>% 
  pivot_longer(!X, names_to = "Celltype", values_to = "Abundance")

# Calculate normalized cell percentage
e2$Total <- sum(e2$Abundance)
e2$Percent <- e2$Abundance / e2$Total

# Plot percent as pie chart
pie(e2$Percent, labels = paste(e2$Celltype, round(e2$Percent * 100, 2), "%"), 
    col = c("#FEBD85", "#8DBAD9", "#DCDD8F", "#E99092", "#8ADDE4", "#C4A9A2", "#45AB84", "#1975BA"), 
    main = "B cell Clone0",
    cex = 0.8)

# Save data for spots with B cell clone 0
e2_all_clone0_spots$cellid <- gsub("TumE2_", "", e2_all_clone0_spots$X)
#top10 <- e2_all_clone0_spots %>% dplyr::arrange(desc(clone0)) %>% head(n = 10)

e2 <- e2_agg %>% dplyr::filter(X %in% e2_all_clone0_spots$cellid) %>% 
  pivot_longer(!X, names_to = "Celltype", values_to = "Abundance")

# Calculate normalized cell percentage
e2 <- e2 %>% dplyr::group_by(X) %>% mutate(Total = sum(Abundance))
e2$Percent <- round(e2$Abundance / e2$Total * 100, 2)

e2_df <- e2 %>% dplyr::select(X, Celltype, Percent) %>% 
  pivot_wider(values_from = "Percent", names_from = "Celltype")

# Get QuPath prediction
qupath <- read.csv("/Users/tili/Desktop/CIIR/results/cell2location/Merged_correlation_results/BCSA2TumE2_correlation_matrix.csv")

# Filter out spots with clone 61
qupath <- qupath %>% dplyr::filter(X %in% e2_df$X) %>% 
  dplyr::select(X, tumor_per, immune_per, stroma_per)

e2_final <- merge(e2_df, qupath, by = "X")

openxlsx::write.xlsx(e2_final, file = "/Users/tili/Desktop/CIIR/results/tables/BCSA2TumE2_B_cell_clone0_all_spots_deconvolution_w_qupath.xlsx")

############### BCSA3TumA1 - Clone61: TumA1_ATACGTTATGCACGGA-1

a1 <- read.csv("/Users/tili/Desktop/CIIR/results/cell2location/BCSA3TumA1_q05.csv")
colnames(a1) <- gsub("q05cell_abundance_w_sf_", "", colnames(a1))

# Aggregate to major level
a1$Endothelial <- rowSums(a1[which(str_detect(colnames(a1), 
                               "Endothelial"))])
a1$CAFs <- rowSums(a1[which(str_detect(colnames(a1), 
                               "CAF"))])
a1$PVLs <- rowSums(a1[which(str_detect(colnames(a1), 
                                      "PVL|Cycling.PVL"))])
a1$Cancer <- rowSums(a1[which(str_detect(colnames(a1), 
                                      "Cancer"))])
a1$B.cells <- rowSums(a1[which(str_detect(colnames(a1), 
                                      "B.cells"))])
a1$T.cells_ILCs <- rowSums(a1[which(str_detect(colnames(a1), 
                                      "T.cells|NK"))])
a1$Plasmablasts <- rowSums(a1[which(str_detect(colnames(a1), 
                                      "Plasmablasts"))])
a1$Myeloid <- rowSums(a1[which(str_detect(colnames(a1), 
                                      "DCs|Monocyte|Macrophage|Cycling_Myeloid"))])

a1_agg <- a1[,c(1, 28, 31:37)]

a1 <- a1_agg %>% dplyr::filter(X == "ATACGTTATGCACGGA-1") %>% 
  pivot_longer(!X, names_to = "Celltype", values_to = "Abundance")

# Calculate normalized cell percentage
a1$Total <- sum(a1$Abundance)
a1$Percent <- a1$Abundance / a1$Total

# Plot percent as pie chart
pie(a1$Percent, labels = paste(a1$Celltype, round(a1$Percent * 100, 2), "%"), 
    col = c("#FEBD85", "#8DBAD9", "#DCDD8F", "#E99092", "#8ADDE4", "#C4A9A2", "#45AB84", "#1975BA"), 
    main = "T cell Clone61",
    cex = 0.8)

# Save data for top10 spots with T cell clone 61
a1_all_clone61_spots$cellid <- gsub("TumA1_", "", a1_all_clone61_spots$X)
#top10 <- a1_all_clone61_spots %>% dplyr::arrange(desc(clone61)) %>% head(n = 10)

a1 <- a1_agg %>% dplyr::filter(X %in% a1_all_clone61_spots$cellid) %>% 
  pivot_longer(!X, names_to = "Celltype", values_to = "Abundance")

# Calculate normalized cell percentage
a1 <- a1 %>% dplyr::group_by(X) %>% mutate(Total = sum(Abundance))
a1$Percent <- round(a1$Abundance / a1$Total * 100, 2)

a1_df <- a1 %>% dplyr::select(X, Celltype, Percent) %>% 
  pivot_wider(values_from = "Percent", names_from = "Celltype")

# Get QuPath prediction
qupath <- read.csv("/Users/tili/Desktop/CIIR/results/cell2location/Merged_correlation_results/BCSA3TumA1_correlation_matrix.csv")

# Filter out spots with clone 61
qupath <- qupath %>% dplyr::filter(X %in% a1_df$X) %>% 
  dplyr::select(X, tumor_per, immune_per, stroma_per)

a1_final <- merge(a1_df, qupath, by = "X")

openxlsx::write.xlsx(a1_final, file = "/Users/tili/Desktop/CIIR/results/tables/BCSA3TumA1_T_cell_clone61_all_spots_deconvolution_w_qupath.xlsx")

```

## session info

```{r session info}
sessionInfo()
```

